Reinforcements = {
	{Type = "Vgr_Interceptor", Weight = 1}, 
	{Type = "Vgr_MultiroleFighter", Weight = 2}, 
	{Type = "Vgr_HeavyFighter", Weight = 3}, 
	{Type = "Vgr_HeavyBomber", Weight = 3}, 
	{Type = "Vgr_Bomber", Weight = 2}, 
	{Type = "Vgr_HeavyMissileFrigate", Weight = 2}, 
	{Type = "Vgr_AssaultFrigate", Weight = 3},
	{Type = "Vgr_GunFrigate", Weight = 3}, 
	{Type = "Vgr_CrusaderFrigate", Weight = 2}, 
	{Type = "Vgr_ArtilleryFrigate", Weight = 2}, 
	{Type = "Vgr_Destroyer", Weight = 3},
	{Type = "Vgr_Battleship", Weight = 4}, 
	{Type = "Vgr_HeavyDestroyer", Weight = 3}, 
	{Type = "Vgr_LightCruiser", Weight = 3}, 
	{Type = "Vgr_Cruiser", Weight = 3}, 
	{Type = "Vgr_MultilanceCorvette", Weight = 3}, 
	{Type = "Vgr_MissileCorvette", Weight = 3}, 
	{Type = "Vgr_LaserCorvette", Weight = 3},
}