aitrace("LOADING HIIGARAN UPGRADE INFO")
rt_mothership = {
  health = {
    MOTHERSHIPHEALTHUPGRADE1,
    MOTHERSHIPHEALTHUPGRADE2,
  },
  speed = {
    MOTHERSHIPMAXSPEEDUPGRADE1,
    MOTHERSHIPMAXSPEEDUPGRADE2,
  },
}
rt_carrier = {
  health = {
    CARRIERHEALTHUPGRADE1,
    CARRIERHEALTHUPGRADE2,
  },
  speed = {
    CARRIERMAXSPEEDUPGRADE1,
    CARRIERMAXSPEEDUPGRADE2,
  },
}
rt_lightcarrier = {
  health = {
    LIGHTCARRIERHEALTHUPGRADE1,
    LIGHTCARRIERHEALTHUPGRADE2,
  },
  speed = {
    LIGHTCARRIERMAXSPEEDUPGRADE1,
    LIGHTCARRIERMAXSPEEDUPGRADE2,
  },
}
rt_fighter = {
  interceptor = {
    INTERCEPTORMAXSPEEDUPGRADE1,
    INTERCEPTORMAXSPEEDUPGRADE2,
  },
  heavyfighter = {
    HEAVYFIGHTERMAXSPEEDUPGRADE1,
    HEAVYFIGHTERMAXSPEEDUPGRADE2,
  },
  strikefighter = {
    STRIKEFIGHTERMAXSPEEDUPGRADE1,
    STRIKEFIGHTERMAXSPEEDUPGRADE2,
  },
  beamfighter = {
    BEAMFIGHTERMAXSPEEDUPGRADE1,
    BEAMFIGHTERMAXSPEEDUPGRADE2,
  },
  bomber = {
    ATTACKBOMBERMAXSPEEDUPGRADE1,
    ATTACKBOMBERMAXSPEEDUPGRADE2,
  },
  heavybomber = {
    HEAVYBOMBERMAXSPEEDUPGRADE1,
    HEAVYBOMBERMAXSPEEDUPGRADE2,
  },
}
rt_corvette = {
  assault = {
    health = {
      ASSAULTCORVETTEHEALTHUPGRADE1,
      ASSAULTCORVETTEHEALTHUPGRADE2,
    },
    speed = {
      ASSAULTCORVETTEMAXSPEEDUPGRADE1,
      ASSAULTCORVETTEMAXSPEEDUPGRADE2,
    },
  },
  pulsar = {
    health = {
      PULSARCORVETTEHEALTHUPGRADE1,
      PULSARCORVETTEHEALTHUPGRADE2,
    },
    speed = {
      PULSARCORVETTEMAXSPEEDUPGRADE1,
      PULSARCORVETTEMAXSPEEDUPGRADE2,
    },
  },
  multi = {
    health = {
      MULTIGUNCORVETTEHEALTHUPGRADE1,
      MULTIGUNCORVETTEHEALTHUPGRADE2,
    },
    speed = {
      MULTIGUNCORVETTEMAXSPEEDUPGRADE1,
      MULTIGUNCORVETTEMAXSPEEDUPGRADE2,
    },
  },
  siege = {
    health = {
      SIEGECORVETTEHEALTHUPGRADE1,
      SIEGECORVETTEHEALTHUPGRADE2,
    },
    speed = {
      SIEGECORVETTEMAXSPEEDUPGRADE1,
      SIEGECORVETTEMAXSPEEDUPGRADE2,
    },
  },
}
rt_frigate = {
  torpedo = {
    health = {
      TORPEDOFRIGATEHEALTHUPGRADE1,
      TORPEDOFRIGATEHEALTHUPGRADE2,
    },
    speed = {
      TORPEDOFRIGATEMAXSPEEDUPGRADE1,
      TORPEDOFRIGATEMAXSPEEDUPGRADE2,
    },
  },
  ioncannon = {
    health = {
      IONCANNONFRIGATEHEALTHUPGRADE1,
      IONCANNONFRIGATEHEALTHUPGRADE2,
    },
    speed = {
      IONCANNONFRIGATEMAXSPEEDUPGRADE1,
      IONCANNONFRIGATEMAXSPEEDUPGRADE2,
    },
  },
  assault = {
    health = {
      ASSAULTFRIGATEHEALTHUPGRADE1,
      ASSAULTFRIGATEHEALTHUPGRADE2,
    },
    speed = {
      ASSAULTFRIGATEMAXSPEEDUPGRADE1,
      ASSAULTFRIGATEMAXSPEEDUPGRADE2,
    },
  },
  gun = {
    health = {
      GUNFRIGATEHEALTHUPGRADE1,
      GUNFRIGATEHEALTHUPGRADE2,
    },
    speed = {
      GUNFRIGATEMAXSPEEDUPGRADE1,
      GUNFRIGATEMAXSPEEDUPGRADE2,
    },
  },
  missile = {
    health = {
      MISSILEFRIGATEHEALTHUPGRADE1,
      MISSILEFRIGATEHEALTHUPGRADE2,
    },
    speed = {
      MISSILEFRIGATEMAXSPEEDUPGRADE1,
      MISSILEFRIGATEMAXSPEEDUPGRADE2,
    },
  },
  plasma = {
    health = {
      PLASMAFRIGATEHEALTHUPGRADE1,
      PLASMAFRIGATEHEALTHUPGRADE2,
    },
    speed = {
      PLASMAFRIGATEMAXSPEEDUPGRADE1,
      PLASMAFRIGATEMAXSPEEDUPGRADE2,
    },
  },
}
rt_battlecruiser = {
  health = {
    BATTLECRUISERHEALTHUPGRADE1,
    BATTLECRUISERHEALTHUPGRADE2,
  },
  speed = {
    BATTLECRUISERMAXSPEEDUPGRADE1,
    BATTLECRUISERMAXSPEEDUPGRADE2,
  },
}
rt_lightcruiser = {
  health = {
    LIGHTCRUISERHEALTHUPGRADE1,
    LIGHTCRUISERHEALTHUPGRADE2,
  },
  speed = {
    LIGHTCRUISERMAXSPEEDUPGRADE1,
    LIGHTCRUISERMAXSPEEDUPGRADE2,
  },
}
rt_cruiser = {
  health = {
    CRUISERHEALTHUPGRADE1,
    CRUISERHEALTHUPGRADE2,
  },
  speed = {
    CRUISERMAXSPEEDUPGRADE1,
    CRUISERMAXSPEEDUPGRADE2,
  },
}
rt_destroyer = {
  DESTROYERHEALTHUPGRADE1,
  DESTROYERMAXSPEEDUPGRADE1,
  DESTROYERHEALTHUPGRADE2,
  DESTROYERMAXSPEEDUPGRADE2,
}
rt_battleship = {
  BATTLESHIPHEALTHUPGRADE1,
  BATTLESHIPMAXSPEEDUPGRADE1,
  BATTLESHIPHEALTHUPGRADE2,
  BATTLESHIPMAXSPEEDUPGRADE2,
}
rt_lrdestroyer = {
  LRDESTROYERHEALTHUPGRADE1,
  LRDESTROYERMAXSPEEDUPGRADE1,
  LRDESTROYERHEALTHUPGRADE2,
  LRDESTROYERMAXSPEEDUPGRADE2,
}
rt_shipyard = {
  health = {
    SHIPYARDHEALTHUPGRADE1,
    SHIPYARDHEALTHUPGRADE2,
  },
  speed = {
    SHIPYARDMAXSPEEDUPGRADE1,
    SHIPYARDMAXSPEEDUPGRADE2,
  },
}
rt_platform = {
  gunturret = {
    GUNTURRETHEALTHUPGRADE1,
    GUNTURRETHEALTHUPGRADE2,
  },
  ionturret = {
    PULSARTURRETHEALTHUPGRADE1,
    PULSARTURRETHEALTHUPGRADE2,
  },
  ionturret = {
    IONTURRETHEALTHUPGRADE1,
    IONTURRETHEALTHUPGRADE2,
  },
}
rt_collector = {
  RESOURCECOLLECTORHEALTHUPGRADE1,
  RESOURCECOLLECTORHEALTHUPGRADE2,
}
rt_refinery = {
  RESOURCECONTROLLERHEALTHUPGRADE1,
  RESOURCECONTROLLERHEALTHUPGRADE2,
}
rt_hyperspace = {
  cost = {
    HYPERSPACECOSTUPGRADE1,
    HYPERSPACECOSTUPGRADE2,
  },
  transittime = {
    HYPERSPACETRANSITTIMEUPGRADE1,
    HYPERSPACETRANSITTIMEUPGRADE2,
  },
}
