Ship = 0
SubSystem = 1
build = {
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Production_Fighter",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7100",
    Description = "$7101",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_CO_Production_Fighter",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7100",
    Description = "$7101",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Production_Fighter",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7100",
    Description = "$7101",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Production_Corvette",
    RequiredResearch = "CorvetteTech",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7102",
    Description = "$7103",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_CO_Production_Corvette",
    RequiredResearch = "CorvetteTech",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7102",
    Description = "$7103",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Production_Corvette",
    RequiredResearch = "CorvetteTech",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7102",
    Description = "$7103",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Production_Frigate",
    RequiredResearch = "FrigateTech",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7104",
    Description = "$7105",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_CO_Production_Frigate",
    RequiredResearch = "FrigateTech",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7104",
    Description = "$7105",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Production_Frigate",
    RequiredResearch = "FrigateTech",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7104",
    Description = "$7105",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Module_PlatformControl",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7108",
    Description = "$7109",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Module_PlatformControl",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7108",
    Description = "$7109",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Production_CapShip",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7106",
    Description = "$7107",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_SY_Production_CapShip",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 1,
    DisplayedName = "$7106",
    Description = "$7107",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Module_Research",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 2,
    DisplayedName = "$7110",
    Description = "$7111",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Module_Research",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 2,
    DisplayedName = "$7110",
    Description = "$7111",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Module_CloakGenerator",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 3,
    DisplayedName = "$7118",
    Description = "$7119",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Module_CloakGenerator",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 3,
    DisplayedName = "$7118",
    Description = "$7119",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Module_HyperspaceInhibitor",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 4,
    DisplayedName = "$7116",
    Description = "$7117",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Module_HyperspaceInhibitor",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 4,
    DisplayedName = "$7116",
    Description = "$7117",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Module_FireControl",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 5,
    DisplayedName = "$7120",
    Description = "$7121",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Module_FireControl",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 5,
    DisplayedName = "$7120",
    Description = "$7121",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Module_Hyperspace",
    RequiredResearch = "HyperspaceGateTech",
    RequiredShipSubSystems = "",
    DisplayPriority = 6,
    DisplayedName = "$7114",
    Description = "$7115",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Module_Hyperspace",
    RequiredResearch = "HyperspaceGateTech",
    RequiredShipSubSystems = "",
    DisplayPriority = 6,
    DisplayedName = "$7114",
    Description = "$7115",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Sensors_AdvancedArray",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 7,
    DisplayedName = "$7122",
    Description = "$7123",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Sensors_AdvancedArray",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 7,
    DisplayedName = "$7122",
    Description = "$7123",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Sensors_DetectHyperspace",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 8,
    DisplayedName = "$7126",
    Description = "$7127",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Sensors_DetectHyperspace",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 8,
    DisplayedName = "$7126",
    Description = "$7127",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Module_HarvestControl",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 9,
    DisplayedName = "Harvest Control Module",
    Description = "Increases harvesting effeicency on any harvesting operations within area",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_c_sensors_defensesuite",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 10,
    DisplayedName = "Anti-Frigate Defense Suite",
    Description = "<b>Barrel #:</b> 4 \n<b>Type:</b> Fast Torpedo \n<b>Damage:</b> 1000-1500 \n<b>Burst Damage:</b> 750-2000 \n<b>Burst Radius:</b> 150 \n<b>Range:</b> 5000 \n<b>Reload:</b> 18 \n\n<b>Additional Armaments:</b> \n1x2 Medium Kinetic Turret \n2x1 Light Missile Hull Defense Launchers",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_c_sensors_fightersuite",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 11,
    DisplayedName = "Anti-Strike Craft Defense Suite",
    Description = "<b>Barrel #:</b> 10 \n<b>Type:</b> Cluster Torpedo \n<b>Damage:</b> 4x 110-200 \n<b>Burst Damage:</b> 4x 150-300 \n<b>Burst Radius:</b> 50 \n<b>Range:</b> 5000 \n<b>Reload:</b> 30 \n\n<b>Additional Armaments:</b> \n1x4 Rapid Flak Turret \n2x1 Light Missile Hull Defense Launchers",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_c_module_SMS",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 11,
    DisplayedName = "Heavy Missile Volley Module",
    Description = "<b>Barrel #:</b> 20 \n<b>Type:</b> Fast Torpedo \n<b>Damage:</b> 1000-1500 \n<b>Burst Damage:</b> 750-2000 \n<b>Burst Radius:</b> 150 \n<b>Range:</b> 6000 \n<b>Reload:</b> 30",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Scout",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 20,
    DisplayedName = "$7130",
    Description = "<b>Ship Class:</b> Fighter \n<b>Sub Class:</b> Scout \n<b>Role:</b> Reconnaissance \n<b>Prerequisites:</b> N\A \n<b>Strong vs:</b> None \n<b>Weak vs:</b> All \n\n<b>Description:</b> \nPrimarily used for reconnaissance, can also be equipped with EMP weapon systems.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Interceptor",
    RequiredResearch = "",
    RequiredShipSubSystems = "FighterProduction | HeavyFusionMissileLauncherBC",
    DisplayPriority = 21,
    DisplayedName = "$7132",
    Description = "<b>Ship Class:</b> Fighter \n<b>Sub Class:</b> Dogfighter \n<b>Role:</b> Anti-Fighter \n<b>Prerequisites:</b> Fighter Facility & Multi-Role Fighter Research \n<b>Strong vs:</b> Fighters \n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nArmed with a cannon, and light anti-fighter missiles, the intercetor with its speed is an excellent anti-fighter platform.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_HeavyFighter",
    RequiredResearch = "heavyfighterchassis",
    RequiredShipSubSystems = "FighterProduction | HeavyFusionMissileLauncherBC",
    DisplayPriority = 24,
    DisplayedName = "Heavy Fighter",
    Description = "<b>Ship Class:</b> Fighter \n<b>Sub Class:</b> Heavy Dogfighter \n<b>Role:</b> Anti-Fighter \n<b>Prerequisites:</b> Fighter Facility, Multi-Role Fighter Research, and Heavy Fighter Research \n<b>Strong vs:</b> Fighters \n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nThis fighter carries double the weapon systems of a multirole fighter and more armor, but it comes at a steeper price, and decreased manuverability.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_StrikeFighter",
    RequiredResearch = "FighterLasers",
    RequiredShipSubSystems = "FighterProduction | HeavyFusionMissileLauncherBC",
    DisplayPriority = 25,
    DisplayedName = "Strike Fighter",
    Description = "<b>Ship Class:</b> Fighter \n<b>Sub Class:</b> Fighter/Bomber \n<b>Role:</b> Anti-Ship \n<b>Prerequisites:</b> Fighter Facility & Strike Fighter Research \n<b>Strong vs:</b> None \n<b>Weak vs:</b> None \n\n<b>Description:</b> \nA 'Jack of all trades' style of fighter, the strike fighter is a light fighter which sports a rapid fire plasma projection array, making it effective vs fighters, and frigates alike, but not really all that great at either.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_LanceFighter",
    RequiredResearch = "LanceBeams",
    RequiredShipSubSystems = "FighterProduction | HeavyFusionMissileLauncherBC",
    DisplayPriority = 26,
    DisplayedName = "$7136",
    Description = "<b>Ship Class:</b> Fighter \n<b>Sub Class:</b> Fighter \n<b>Role:</b> Anti-Corvette \n<b>Prerequisites:</b> Fighter Facility & Lance Fighter Research \n<b>Strong vs:</b> Corvettes \n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nBasically a fighter with a Plasma Lance strapped to it, and a larger reactor to compensate.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Bomber",
    RequiredResearch = "PlasmaBombs",
    RequiredShipSubSystems = "FighterProduction | HeavyFusionMissileLauncherBC",
    DisplayPriority = 27,
    DisplayedName = "$7134",
    Description = "<b>Ship Class:</b> Fighter \n<b>Sub Class:</b> Bomber \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Fighter Facility & Bomber Research \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nSporting dual plasma projection arrays, the bomber, although slow, can bring down intense firepower onto a single slower moving target. Plasma Arrays can be upgraded.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_heavybomber",
    RequiredResearch = "strikemissiles",
    RequiredShipSubSystems = "FighterProduction | HeavyFusionMissileLauncherBC",
    DisplayPriority = 28,
    DisplayedName = "Strike Bomber",
    Description = "<b>Ship Class:</b> Fighter \n<b>Sub Class:</b> Heavy Bomber \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Fighter Facility & Strike Bomber Research \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nUsing a design to reduce attack time, the Strike Bomber uses two salvo fired light torpedo racks and dual heavy kinetic cannons. This bomber benefits from increased firepower, and nimble speeds, but no increase in armor.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_MissileCorvette",
    RequiredResearch = "",
    RequiredShipSubSystems = "CorvetteProduction | HeavyFusionMissileLauncherBC",
    DisplayPriority = 50,
    DisplayedName = "$7138",
    Description = "<b>Ship Class:</b> Corvette \n<b>Sub Class:</b> Light \n<b>Role:</b> Anti-Fighter \n<b>Prerequisites:</b> Corvette Facility \n<b>Strong vs:</b> Fighters \n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nArmed with two anti-strike craft missile launchers, and decent speed, this corvette is an excellent anti-fighter corvette, although its light armor should see it used in a support role.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_LaserCorvette",
    RequiredResearch = "CorvetteLaser",
    RequiredShipSubSystems = "CorvetteProduction | HeavyFusionMissileLauncherBC",
    DisplayPriority = 51,
    DisplayedName = "$7140",
    Description = "<b>Ship Class:</b> Corvette \n<b>Sub Class:</b> Light \n<b>Role:</b> Anti-Frigate \n<b>Prerequisites:</b> Corvette Facility & Laser Corvette Research \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nArmed with two forward mounted light laser cannons, the Laser Corvette is a very effective anti ship platform, although its light armor should see it used mainly in support role.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_multilancecorvette",
    RequiredResearch = "microlanceturret",
    RequiredShipSubSystems = "CorvetteProduction | HeavyFusionMissileLauncherBC",
    DisplayPriority = 52,
    DisplayedName = "Multi Lance Corvette",
    Description = "<b>Ship Class:</b> Corvette \n<b>Sub Class:</b> Medium \n<b>Role:</b> Anti-Corvette \n<b>Prerequisites:</b> Corvette Facility & Multi-Lance Corvette Research \n<b>Strong vs:</b> Corvettes \n<b>Weak vs:</b> Fighters, Capital Ships \n\n<b>Description:</b> \nArmed with two dual barreled plasma lances, this corvette is excellent at anti-corvette roles.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_trinitycorvette",
    RequiredResearch = "microtrinityarray",
    RequiredShipSubSystems = "CorvetteProduction | HeavyFusionMissileLauncherBC",
    DisplayPriority = 53,
    DisplayedName = "Trinity Corvette",
    Description = "<b>Ship Class:</b> Corvette \n<b>Sub Class:</b> Heavy \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Corvette Facility, Laser Corvette Research, and Trinity Corvette Research \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nPractically a corvette built around a gun, the trinity corvette uses a smaller version of the Battlecruisers trinity cannon, and also comes with two dual barreled light kinetic turrets, but are slow, and should still have strike craft escort.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_MinelayerCorvette",
    RequiredResearch = "CorvetteGraviticAttraction",
    RequiredShipSubSystems = "CorvetteProduction | HeavyFusionMissileLauncherBC",
    DisplayPriority = 54,
    DisplayedName = "$7142",
    Description = "<b>Ship Class:</b> Corvette \n<b>Sub Class:</b> Medium \n<b>Role:</b> Area Denial \n<b>Prerequisites:</b> Corvette Facility & Minelayer Corvette Research \n<b>Strong vs:</b> N\A \n<b>Weak vs:</b> N\A \n\n<b>Description:</b> \nThis corvette is designed for one purpose: to drop mines.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_CommandCorvette",
    RequiredResearch = "CorvetteCommand",
    RequiredShipSubSystems = "CorvetteProduction | HeavyFusionMissileLauncherBC",
    DisplayPriority = 55,
    DisplayedName = "$7144",
    Description = "$7145",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_HeavyMissileFrigate",
    RequiredResearch = "",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 70,
    DisplayedName = "$7148",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Light \n<b>Role:</b> Anti-Frigate \n<b>Prerequisites:</b> Frigate Facility \n<b>Strong vs:</b> Frigates \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nArmed with two heavy missile launching bays, a light missile launcher, and a few light hull defense weapons, this ship is most effective versus frigates.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_AssaultFrigate",
    RequiredResearch = "",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 71,
    DisplayedName = "Flak Frigate",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Light \n<b>Role:</b> Anti-Strike Craft \n<b>Prerequisites:</b> Frigate Facility \n<b>Strong vs:</b> Fighters, Corvettes \n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nArmed with three flak turrets, a light missile launcher, and a few hull defense points, this frigate is excellent at taking on strike craft, but lacks anti ship firepower.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Gunfrigate",
    RequiredResearch = "",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 72,
    DisplayedName = "Gun Frigate",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Light \n<b>Role:</b> Anti-Frigate \n<b>Prerequisites:</b> Frigate Facility \n<b>Strong vs:</b> Frigates \n<b>Weak vs:</b> Capital Ships \n\n<b>Description:</b> \nRumored to be driven by fighter pilots after promotion, Gun Frigate captains are pretty much that. Armed with two dual barrled medium kinetic cannons, a spinal mounted medium laser array, and a handful of hull defense weapons, this frigate is the defintion of old fashioned combat gone right.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_lancefrigate",
    RequiredResearch = "",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 73,
    DisplayedName = "Lance Frigate",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Light \n<b>Role:</b> Anti-Corvette \n<b>Prerequisites:</b> Frigate Facility \n<b>Strong vs:</b> Fighters, Corvettes \n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nArmed with 2 heavy plasma lance turrets, 1 forward flak cannon and a concussion missile launcher, this frigate excels at swatting corvettes from the sky.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_CrusaderFrigate",
    RequiredResearch = "CrusaderFrigateResearch",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 74,
    DisplayedName = "Crusader Frigate",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Heavy \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Frigate Facility & Crusader Frigate Research \n<b>Strong vs:</b> Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nArmed with a heavy spinally mounted ion cannon, two dual barreled medium kinetic turrets, and a dual barreled laser defense turret, this frigate is heavily armed, and armored, but its low manuverability, make it difficult to bring to bare on faster moving targets.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Artilleryfrigate",
    RequiredResearch = "railgunsystems",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 75,
    DisplayedName = "Artillery Frigate",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Heavy \n<b>Role:</b> Long Range Fire Support \n<b>Prerequisites:</b> Frigate Facility & Artillery Frigate Research \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nArmed with two long range rail guns, a four barreled light kinetic turret, and a coupld hull defense weapons, this frigate can provide excellent fire support while staying fairly safe.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Warfrigate",
    RequiredResearch = "rapiermissilesystem",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 76,
    DisplayedName = "War Frigate: Laser",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Heavy \n<b>Role:</b> Anti-Frigate Superiority \n<b>Prerequisites:</b> Frigate Facility & War Frigate Research \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nBristling with a forward mounted Berzerker laser cannon, a Rapier missile launching bay, two frigate class laser turrets, and an energy cannon PDS turret, this frigate comes with a vengence.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Warfrigate2",
    RequiredResearch = "rapiermissilesystem",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 77,
    DisplayedName = "War Frigate: Missile",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Heavy \n<b>Role:</b> Anti-Frigate Superiority \n<b>Prerequisites:</b> Frigate Facility & War Frigate Research \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nBristling with a forward mounted Berzerker laser cannon, a Rapier missile launching bay, two heavy missile racks, and an energy cannon PDS turret, this frigate comes with a vengence.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_InfiltratorFrigate",
    RequiredResearch = "FrigateInfiltrationTech",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 78,
    DisplayedName = "$7150",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Heavy \n<b>Role:</b> Capture Vessel \n<b>Prerequisites:</b> Frigate Facility & Infiltrator Frigate Research \n<b>Strong vs:</b> N/A \n<b>Weak vs:</b> N/A \n\n<b>Description:</b> \nOriginally designed to be a cheap, and effective way to dump landing pods into orbit of a besieged planet, the infilitrator frigate has had its pods redesigned to bore through the armor of enemy space craft instead.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_EMPfrigate",
    RequiredResearch = "StealthTorpedoResearch & ScoutEMPAbility",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 79,
    DisplayedName = "EMPFrigate",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Medium \n<b>Role:</b> Systems interruption \n<b>Prerequisites:</b> Frigate Facility, Scout EMP ability, and EMP Frigate Research \n<b>Strong vs:</b> N/A \n<b>Weak vs:</b> N/A \n\n<b>Description:</b> \nThis frigates design was brought to the knowledge of Makaan the hard way, while uniting the reaches this design proved very formidable and was incorporated into the Vaygr military almost immediately.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Carrier",
    RequiredResearch = "",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 100,
    DisplayedName = "$7154",
    Description = "<b>Ship Class:</b> Carrier \n<b>Role:</b> Production and forward combat operations \n<b>Prerequisites:</b> Capital Ship Facility \n<b>Strong vs:</b> N/A \n<b>Weak vs:</b> N/A \n\n<b>Description:</b> \nCapable of building up to frigate sized ships, and bringing in shipyards. Although lightly armed, and armored, this ship is an excellent vessel to base, and maintain, a small strike force.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Battleship",
    RequiredResearch = "BattleshipEngines",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 110,
    DisplayedName = "Strike Destroyer",
    Description = "<b>Ship Class:</b> Destroyer \n<b>Role:</b> Escort \n<b>Prerequisites:</b> Capital-Ship Facility, Strike Destroyer Research \n<b>Strong vs:</b> Fighters, Corvettes \n<b>Weak vs:</b> Capital Ships \n\n<b>Armament:</b> \n1x4 Fast torpedo Launchers \n1x1 Heavy Lance Turrets \n2x10 Auxiliary Cluster Missile Tubes \n3x2 Light Missile Defense Turrets \n3x1 Flak Hull Defense Points \n\n<b>Description:</b> \nThis ship is an excellent escort ship, although frequenlty outmatched by other capital ships, this ship is armed to provide support fire for the current battle.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Destroyer",
    RequiredResearch = "DestroyerGuns",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 111,
    DisplayedName = "$7152",
    Description = "<b>Ship Class:</b> Destroyer \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Capital-Ship Facility & Destroyer Research \n<b>Strong vs:</b> Frigates, Capital-Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Armament:</b> \n1x6 Torpedo Launcher \n2x1 Berzerker Laser Turrets \n2x4 Auxiliary Fast Torpedo Launchers \n3x2 Kinetic Defense Turrets \n\n<b>Description:</b> \nCapable of standing its on versus capital ships, and excelling against frigates, this ship does lack an effective Anti-Stike Craft armament, and should be escorted.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_heavydestroyer",
    RequiredResearch = "heavydestroyerchassis",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 112,
    DisplayedName = "Heavy Destroyer",
    Description = "<b>Ship Class:</b> Destroyer \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Capital Ship Facility & Heavy Destroyer Research \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Armament:</b> \n1x6 Torpedo Tubes \n1x1 Spinally Mounted Heavy Laser Cannon \n2x2 Frigate Class Laser Turrets\n1x2 Artillery Turret \n3x2 Light Laser Defense Turrets \n2x4 Light Kinetic Defense Turrets \n\n<b>Description:</b> \nCapable of standing its on versus capital ships, and excelling against frigates, this ship does lack an effective Anti-Stike Craft armament, and should be escorted.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_ShipYard",
    RequiredResearch = "",
    RequiredShipSubSystems = "Hyperspace",
    DisplayPriority = 113,
    DisplayedName = "$7156",
    Description = "$7157",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_lightcruiser",
    RequiredResearch = "CruiserChassis",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 114,
    DisplayedName = "Light Cruiser",
    Description = "<b>Ship Class:</b> Light Cruiser \n<b>Role:</b> Anti-Frigate \n<b>Prerequisites:</b> Capital-Ship Facility & Light Cruiser Research \n<b>Strong vs:</b> None \n<b>Weak vs:</b> None \n\n<b>Armament:</b> \n2x6 Side Launched Torpedo Tubes \n1x4 Berzerker Laser Turret \n2x1 Berzerker Laser Turrets \n2x1 Heavy Plasma Lance Turrets \n1x4 Rapid Flak Turret \n5x4 Light Kinetic Defense Turrets \n\n<b>Description:</b> \nWhile capable of bringing all of its firepower to bear on a single target, this ship specializes in frequent firing weapons best used against frigates.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_cruiser",
    RequiredResearch = "IonCruiserChassis",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 115,
    DisplayedName = "Ion Cruiser",
    Description = "<b>Ship Class:</b> Light Cruiser \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Capital-Ship Facility \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Armament:</b> \n2x1 Ion Cannon Turrets \n1x8 Fusion Missile Tubes \n8x1 Kinetic Turrets \n3x2 Heavy Kinetic Turrets \n1x4 Rapid Flak Turret \n2x1 Pulsating Lance Hull Defense Points \n\n<b>Description:</b> \nWhile not by any means the 'Jack of all trades' its brother the Light Cruiser is, the Ion Cruiser is a very deadly ship capable of bringing intense firepower onto a single target.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Carrier_Ops",
    RequiredResearch = "",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 117,
    DisplayedName = "Battle Carrier",
    Description = "<b>Ship Class:</b> Carrier \n<b>Role:</b> Heavy Combat and Fleet Production \n<b>Prerequisites:</b> Capital Ship Facility \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Armament:</b> \n2x4 Kiloton Missile Launchers\n5x1 Hull Defense Points\n2x Heavy Turret Hardpoints\n2x Light Turret Hardpoints\n\n<b>Description:</b> \nBuilt to survive the stresses of forward combat, while bringing enough firepower to turn the tide, and still being capable building and maintaining a fleet.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_BattleCruiser",
    RequiredResearch = "BattlecruiserIonWeapons",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 120,
    DisplayedName = "$7158",
    Description = "<b>Ship Class:</b> Battlecruiser \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Capital-Ship Facility, Light Cruiser Research, Heavy Cruiser Research, and Battlecruiser research \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Armament:</b> \n1x3 Heavy Trinity Laser Array \n1x8 Heavy Torpedo Tubes \n3x4 Fast Torpedo Tubes \n2x2 Artillery Turrets \n2x2 Heavy Kinetic Turrets \n4x1 Pulsating Plasma Lance Hull Defense Points \n2x2 Gattling Defense Turrets \n6x2 Light Laser Defense Turrets \n\n<b>Description:</b> \nBristling with Anti-Capital ship weapon systems, the Vaygr Battlecruiser is a fearsome Anti-Capital ship, but it should still be escorted.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Alkhalid",
    RequiredResearch = "battleshipchassis",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 121,
    DisplayedName = "Battleship",
    Description = "<b>Ship Class:</b> Battleship \n<b>Role:</b> Anti-Capital Ship Superiority \n<b>Prerequisites:</b> Capital-Ship Facility, Light Cruiser Research, Heavy Cruiser Research, Battleship Research \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Armament:</b> \n2x2 Heavy Ion Cannon Turrets \n1x3 Rapier Missile Launcher \n2x8 Heavy Torpedo Tubes \n2x4 Heavy Torpedo Tubes \n2x4 Heavy Kinetic Turrets \n4x2 Heavy Flak Turrets \n8x1 Heavy Plasma Lance Turrets \n\n<b>Description:</b> \nThe premier Anti-Capital Ship on the battlefield today, when this ship shows up on the scene things tend to get really quiet, really fast.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_WeaponPlatform_gun",
    RequiredResearch = "",
    RequiredShipSubSystems = "PlatformProduction",
    DisplayPriority = 400,
    DisplayedName = "$7160",
    Description = "<b>Ship Class:</b> Weapon Platform \n<b>Role:</b> Anti-Fighter \n<b>Prerequisites:</b> Platform Production Module \n<b>Strong vs:</b> Fighters\n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nArmed with two rapid flak turrets, this platform is an effective anti-fighter defense.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_WeaponPlatform_lance",
    RequiredResearch = "",
    RequiredShipSubSystems = "PlatformProduction",
    DisplayPriority = 401,
    DisplayedName = "Lance Platform",
    Description = "<b>Ship Class:</b> Weapon Platform \n<b>Role:</b> Anti-Corvette \n<b>Prerequisites:</b> Platform Production Module \n<b>Strong vs:</b> Corvettes \n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nArmed with two heavy lance turrets, this platform is an effective anti-corvette defense.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_WeaponPlatform_missile",
    RequiredResearch = "PlatformHeavyMissiles",
    RequiredShipSubSystems = "PlatformProduction",
    DisplayPriority = 402,
    DisplayedName = "$7162",
    Description = "<b>Ship Class:</b> Platform \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Platform Production Module & Missile Platform Research \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nArmed with two four tubes torpedo launchers, this platform is an effective anti-frigate, and capital ship defense.",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_ResourceCollector",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 500,
    DisplayedName = "$7164",
    Description = "$7165",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_ResourceController",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 510,
    DisplayedName = "$7166",
    Description = "$7167",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_HyperSpace_Platform",
    RequiredResearch = "HyperspaceGateTech",
    RequiredShipSubSystems = "PlatformProduction",
    DisplayPriority = 520,
    DisplayedName = "$7174",
    Description = "$7175",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Probe",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 540,
    DisplayedName = "$7168",
    Description = "$7169",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Probe_Prox",
    RequiredResearch = "ProbeProxSensor",
    RequiredShipSubSystems = "",
    DisplayPriority = 550,
    DisplayedName = "$7170",
    Description = "$7171",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Probe_ECM",
    RequiredResearch = "ProbeSensorDisruption",
    RequiredShipSubSystems = "",
    DisplayPriority = 560,
    DisplayedName = "$7172",
    Description = "$7173",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_PlanetKillerMissile",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 612,
    DisplayedName = "Honking big planet killing missile",
    Description = "",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bwm_flak",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 613,
    DisplayedName = "Flak Turret",
    Description = "<b>Barrel #:</b> 4 \n<b>Type:</b> Flak \n<b>Damage:</b> 30 \n<b>Burst Damage:</b> 25-35 \n<b>Burst Radius:</b> 30 \n<b>Range:</b> 5000 \n<b>Reload:</b> 1",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bwm_flak2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 614,
    DisplayedName = "Flak Turret",
    Description = "<b>Barrel #:</b> 4 \n<b>Type:</b> Flak \n<b>Damage:</b> 30 \n<b>Burst Damage:</b> 25-35 \n<b>Burst Radius:</b> 30 \n<b>Range:</b> 5000 \n<b>Reload:</b> 1",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bwm_ion",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 615,
    DisplayedName = "Ion Cannon Turret",
    Description = "<b>Barrel #:</b> 1 \n<b>Type:</b> Ion Cannon \n<b>Damage:</b> 10000 \n<b>Range:</b> 6000 \n<b>Reload:</b> 15",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bwm_ion2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 616,
    DisplayedName = "Ion Cannon Turret",
    Description = "<b>Barrel #:</b> 1 \n<b>Type:</b> Ion Cannon \n<b>Damage:</b> 10000 \n<b>Range:</b> 6000 \n<b>Reload:</b> 15",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bwm_kinetic",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 617,
    DisplayedName = "Kinetic Turret",
    Description = "<b>Barrel #:</b> 3 \n<b>Type:</b> Kinetic \n<b>Damage:</b> 700 \n<b>Range:</b> 6000 \n<b>Reload:</b> 5",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bwm_kinetic2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 618,
    DisplayedName = "Kinetic Turret",
    Description = "<b>Barrel #:</b> 3 \n<b>Type:</b> Kinetic \n<b>Damage:</b> 700 \n<b>Range:</b> 6000 \n<b>Reload:</b> 5",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bwm_artillery",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 619,
    DisplayedName = "Ultra Heavy Kinetic Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Kinetic \n<b>Damage:</b> 1500-1750 \n<b>Range:</b> 6000 \n<b>Reload:</b> 4",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bwm_artillery2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 620,
    DisplayedName = "Ultra Heavy Kinetic Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Kinetic \n<b>Damage:</b> 1500-1750 \n<b>Range:</b> 6000 \n<b>Reload:</b> 4",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bwm_plasma",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 621,
    DisplayedName = "Laser Turret",
    Description = "<b>Barrel #:</b> 1\n<b>Type:</b> Plasma \n<b>Damage:</b> 1250-1750 \n<b>Range:</b> 5000 \n<b>Reload:</b> 3",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bwm_plasma2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 622,
    DisplayedName = "Laser Turret",
    Description = "<b>Barrel #:</b> 1\n<b>Type:</b> Plasma \n<b>Damage:</b> 1250-1750 \n<b>Range:</b> 5000 \n<b>Reload:</b> 3",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bwm_rapier",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 623,
    DisplayedName = "Rapier Turret",
    Description = "<b>Barrel #:</b> 1 \n<b>Type:</b> Rapier Missile \n<b>Damage:</b> 5000-8000 \n<b>Burst Damage:</b> 12000-15000 \n<b>Burst Radius:</b>  350 \n<b>Range:</b> 6000 \n<b>Reload:</b> 30",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bwm_rapier2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 624,
    DisplayedName = "Rapier Turret",
    Description = "<b>Barrel #:</b> 1 \n<b>Type:</b> Rapier Missile \n<b>Damage:</b> 5000-8000 \n<b>Burst Damage:</b> 12000-15000 \n<b>Burst Radius:</b>  350 \n<b>Range:</b> 6000 \n<b>Reload:</b> 30",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bwm_wp",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 625,
    DisplayedName = "Weapon Platform",
    Description = "<b>Barrel #:</b> 8 \n<b>Type:</b> Fast Torpedo \n<b>Damage:</b> 1000-1250 \n<b>Burst Damage:</b> 750-1000 \n<b>Burst Radius:</b> 120 \n<b>Range:</b> 5000 \n<b>Reload:</b> 30 \n\n<b>Additional Armaments:</b> /n4x1 Light Kinetic Defense Turret",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bwm_wp2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 626,
    DisplayedName = "Weapon Platform",
    Description = "<b>Barrel #:</b> 8 \n<b>Type:</b> Fast Torpedo \n<b>Damage:</b> 1000-1250 \n<b>Burst Damage:</b> 750-1000 \n<b>Burst Radius:</b> 120 \n<b>Range:</b> 5000 \n<b>Reload:</b> 30 \n\n<b>Additional Armaments:</b> /n4x1 Light Kinetic Defense Turret",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bpd_gatling",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 627,
    DisplayedName = "Kinetic Gatling PDW",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Gattling \n<b>Damage:</b> 30 \n<b>Range:</b> 5950 \n<b>Burst of:</b> 15 \n<b>Every:</b> 2.2 seconds",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bpd_gatling2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 628,
    DisplayedName = "Kinetic Gatling PDW",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Gattling \n<b>Damage:</b> 30 \n<b>Range:</b> 5950 \n<b>Burst of:</b> 15 \n<b>Every:</b> 2.2 seconds",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bpd_flak",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 629,
    DisplayedName = "Rapid Flak PDW",
    Description = "<b>Barrel #:</b> 4 \n<b>Type:</b> Flak \n<b>Damage:</b> 30 \n<b>Burst Damage:</b> 25-35 \n<b>Burst Radius:</b> 30 \n<b>Range:</b> 5000 \n<b>Reload:</b> 1",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bpd_flak2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 630,
    DisplayedName = "Rapid Flak PDW",
    Description = "<b>Barrel #:</b> 4 \n<b>Type:</b> Flak \n<b>Damage:</b> 30 \n<b>Burst Damage:</b> 25-35 \n<b>Burst Radius:</b> 30 \n<b>Range:</b> 5000 \n<b>Reload:</b> 1",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bpd_pulsar",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 631,
    DisplayedName = "Heavy Plasma lance PDW",
    Description = "<b>Barrel #:</b> 1 \n<b>Type:</b> Plasma Lance \n<b>Damage:</b> 450-650 \n<b>Burst Damage:</b> 50-75 x2 \n<b>Burst Radius:</b> 90 \n<b>Range:</b> 5500 \n<b>Reload:</b> 1",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bpd_pulsar2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 632,
    DisplayedName = "Heavy Plasma lance PDW",
    Description = "<b>Barrel #:</b> 1 \n<b>Type:</b> Plasma Lance \n<b>Damage:</b> 450-650 \n<b>Burst Damage:</b> 50-75 x2 \n<b>Burst Radius:</b> 90 \n<b>Range:</b> 5500 \n<b>Reload:</b> 1",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bpd_missile",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 633,
    DisplayedName = "Cluster Missile PDW",
    Description = "<b>Barrel #:</b> 1 \n<b>Type:</b> Missile \n<b>Damage:</b> 110-200 x4 \n<b>Burst Damage:</b> 90 x4 \n<b>Burst Radius:</b> 32 \n<b>Range:</b> 5000 \n<b>Reload:</b> 4",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_bpd_missile2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 634,
    DisplayedName = "Cluster Missile PDW",
    Description = "<b>Barrel #:</b> 1 \n<b>Type:</b> Missile \n<b>Damage:</b> 110-200 x4 \n<b>Burst Damage:</b> 90 x4 \n<b>Burst Radius:</b> 32 \n<b>Range:</b> 5000 \n<b>Reload:</b> 4",
  },
}