Reinforcements = {
	{Type = "Vgr_Interceptor", Weight = 1},
	{Type = "Vgr_MultiroleFighter", Weight = 1},
	{Type = "Vgr_HeavyFighter", Weight = 1},
	{Type = "Vgr_StrikeFighter", Weight = 1},
	{Type = "Vgr_Defender", Weight = 1},
	{Type = "Vgr_LanceFighter", Weight = 1},
	{Type = "Vgr_Bomber", Weight = 1},
	{Type = "Vgr_HeavyBomber", Weight = 1},
	{Type = "Vgr_MissileCorvette", Weight = 1},
	{Type = "Vgr_LaserCorvette", Weight = 1},
	{Type = "Vgr_MultilanceCorvette", Weight = 1},
	{Type = "Vgr_AssaultFrigate", Weight = 1},
	{Type = "Vgr_GunFrigate", Weight = 1},
	{Type = "Vgr_HeavyMissileFrigate", Weight = 1},
	{Type = "Vgr_CrusaderFrigate", Weight = 1},
	{Type = "Vgr_WarFrigate", Weight = 1},
	{Type = "Vgr_WeaponPlatform_gun", Weight = -1},
}
