Ship = 0
SubSystem = 1
build = {
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_LC_Production_Fighter",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7000",
    Description = "$7001",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_C_Production_Fighter",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7000",
    Description = "$7001",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_MS_Production_Fighter",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7000",
    Description = "$7001",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_LC_Production_Corvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 0,
    DisplayedName = "$7002",
    Description = "$7003",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_C_Production_Corvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 0,
    DisplayedName = "$7002",
    Description = "$7003",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_MS_Production_Corvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 0,
    DisplayedName = "$7002",
    Description = "$7003",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_C_Production_Frigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 0,
    DisplayedName = "$7004",
    Description = "$7005",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_MS_Production_Frigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 0,
    DisplayedName = "$7004",
    Description = "$7005",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_MS_Production_CapShip",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7006",
    Description = "$7007",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_SY_Production_CapShip",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7006",
    Description = "$7007",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_LC_Module_Defensefieldshield",
    RequiredResearch = "DefenseFieldFrigateShield",
    RequiredFleetSubSystems = "",
    DisplayPriority = 1,
    DisplayedName = "Defense Field Subsystem.",
    Description = "<b>Description:</b>Modular Defensive subsystem. \n\n<b>Prerequisites:</b>Defense field research",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_C_Module_HarvestControl",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 1,
    DisplayedName = "Harvest Control Module",
    Description = "<b>Description:</b>A Subsystem capable of increasing harvesting effienciency of any nearby resource operations",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_ACV_Module_BuildSpeed",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 1,
    DisplayedName = "Manufacturing Control Module",
    Description = "<b>Description:</b>A Subsystem capable of increasing production speeds by 30 percent.",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_ACV_Module_ExpertCrew",
    RequiredResearch = "",
    RequiredFleetSubSystems = "AdvancedResearch",
    DisplayPriority = 2,
    DisplayedName = "Expert Crew Module",
    Description = "<b>Description:</b>Housing for teams of military crew capable of increasing resourcing operations, docked ship repair, and enables research upgrades.",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_ACV_Module_PlatformControl",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 10,
    DisplayedName = "$7008",
    Description = "$7009",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_C_Module_PlatformControl",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 10,
    DisplayedName = "$7008",
    Description = "$7009",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_MS_Module_PlatformControl",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 20,
    DisplayedName = "$7008",
    Description = "$7009",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_ACV_Module_Research",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7010",
    Description = "$7011",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_C_Module_Research",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7010",
    Description = "$7011",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_MS_Module_Research",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7010",
    Description = "$7011",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_ACV_Module_ResearchAdvanced",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 10,
    DisplayedName = "$7012",
    Description = "$7013",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_C_Module_ResearchAdvanced",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 10,
    DisplayedName = "$7012",
    Description = "$7013",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_MS_Module_ResearchAdvanced",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 10,
    DisplayedName = "$7012",
    Description = "$7013",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_LC_Module_Hyperspace",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 30,
    DisplayedName = "$7014",
    Description = "$7015",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_ACV_Module_Hyperspace",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 30,
    DisplayedName = "$7014",
    Description = "$7015",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_C_Module_Hyperspace",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 30,
    DisplayedName = "$7014",
    Description = "$7015",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_MS_Module_Hyperspace",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 30,
    DisplayedName = "$7014",
    Description = "$7015",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_ACV_Module_HyperspaceInhibitor",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 40,
    DisplayedName = "$7016",
    Description = "$7017",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_C_Module_HyperspaceInhibitor",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 40,
    DisplayedName = "$7016",
    Description = "$7017",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_MS_Module_HyperspaceInhibitor",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 40,
    DisplayedName = "$7016",
    Description = "$7017",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_LC_Module_CloakGenerator",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 50,
    DisplayedName = "$7018",
    Description = "$7019",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_ACV_Module_CloakGenerator",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 50,
    DisplayedName = "$7018",
    Description = "$7019",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_C_Module_CloakGenerator",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 50,
    DisplayedName = "$7018",
    Description = "$7019",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_MS_Module_CloakGenerator",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 50,
    DisplayedName = "$7018",
    Description = "$7019",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_ACV_Module_FireControl",
    RequiredResearch = "",
    RequiredFleetSubSystems = "AdvancedResearch",
    DisplayPriority = 60,
    DisplayedName = "$7020",
    Description = "$7021",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_C_Module_FireControl",
    RequiredResearch = "",
    RequiredFleetSubSystems = "AdvancedResearch",
    DisplayPriority = 60,
    DisplayedName = "$7020",
    Description = "$7021",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_MS_Module_FireControl",
    RequiredResearch = "",
    RequiredFleetSubSystems = "AdvancedResearch",
    DisplayPriority = 60,
    DisplayedName = "$7020",
    Description = "$7021",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_ACV_DetectHyperspace",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 150,
    DisplayedName = "$7036",
    Description = "$7037",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_C_Sensors_DetectHyperspace",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 150,
    DisplayedName = "$7036",
    Description = "$7037",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_MS_Sensors_DetectHyperspace",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 150,
    DisplayedName = "$7036",
    Description = "$7037",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_LC_Sensors_AdvancedArray",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 151,
    DisplayedName = "$7022",
    Description = "$7023",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_ACV_AdvancedArray",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 151,
    DisplayedName = "$7022",
    Description = "$7023",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_C_Sensors_AdvancedArray",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 151,
    DisplayedName = "$7022",
    Description = "$7023",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_MS_Sensors_AdvancedArray",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 151,
    DisplayedName = "$7022",
    Description = "$7023",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_LC_Sensors_DetectCloaked",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 152,
    DisplayedName = "$7024",
    Description = "$7025",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_ACV_DetectCloaked",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 152,
    DisplayedName = "$7024",
    Description = "$7025",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_C_Sensors_DetectCloaked",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 152,
    DisplayedName = "$7024",
    Description = "$7025",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_MS_Sensors_DetectCloaked",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 152,
    DisplayedName = "$7024",
    Description = "$7025",
  },
  {
    Type = Ship,
    ThingToBuild = "Kpr_Mover",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 53,
    DisplayedName = "$7913",
    Description = "$7914",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_MS_Production_CorvetteMover",
    RequiredResearch = "",
    RequiredShipSubSystems = "CorvetteProduction",
    DisplayPriority = 10,
    DisplayedName = "$7910",
    Description = "$7911",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_Scout",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 10,
    DisplayedName = "$7030",
    Description = "<b>Ship Class:</b> Fighter \n<b>Sub Class:</b> Scout \n<b>Role:</b> Reconnaissance \n<b>Prerequisites:</b> N\A \n<b>Strong vs:</b> None \n<b>Weak vs:</b> All \n\n<b>Description:</b> \nPrimarily used for reconnaissance, can also be equipped with EMP weapon systems.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_Interceptor",
    RequiredResearch = "",
    RequiredShipSubSystems = "FighterProduction | BCIonBeamTurret",
    DisplayPriority = 20,
    DisplayedName = "$7032",
    Description = "<b>Ship Class:</b> Fighter \n<b>Sub Class:</b> Dogfighter \n<b>Role:</b> Anti-Strike Craft \n<b>Prerequisites:</b> Fighter Facility \n<b>Strong vs:</b> Fighters \n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nArmed with a cannon, and light anti-fighter missiles the interceptor is an effective light anti-stike craft platform.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_Heavyfighter",
    RequiredResearch = "InstaAdvancedFighterTech2",
    RequiredShipSubSystems = "FighterProduction | BCIonBeamTurret",
    DisplayPriority = 21,
    DisplayedName = "Heavy Fighter",
    Description = "<b>Ship Class:</b> Fighter \n<b>Sub Class:</b> Heavy Dogfighter \n<b>Role:</b> Anti-Strike Craft \n<b>Prerequisites:</b> Fighter Facility & Advanced Research Module \n<b>Strong vs:</b> Fighters \n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nThis fighter carries double the weapon systems of a multirole fighter and more armor, but it comes at a steeper price, and decreased manuverability.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_StrikeFighter",
    RequiredResearch = "InstaAdvancedFighterTech2",
    RequiredShipSubSystems = "FighterProduction | BCIonBeamTurret",
    DisplayPriority = 22,
    DisplayedName = "Strike Fighter",
    Description = "<b>Ship Class:</b> Fighter \n<b>Sub Class:</b> Fighter/Bomber \n<b>Role:</b> Anti-Ship \n<b>Prerequisites:</b> Fighter Facility & Advanced Research Module \n<b>Strong vs:</b> None \n<b>Weak vs:</b> None \n\n<b>Description:</b> \nA 'Jack of all trades' style of fighter, the strike fighter is a light fighter which sports a rapid fire plasma projection array, making it effective vs fighters, and frigates alike, but not really all that great at either.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_BeamFighter",
    RequiredResearch = "InstaAdvancedFighterTech2",
    RequiredShipSubSystems = "FighterProduction | BCIonBeamTurret",
    DisplayPriority = 23,
    DisplayedName = "Pulsar Fighter",
    Description = "<b>Ship Class:</b> Fighter \n<b>Sub Class:</b> Fighter \n<b>Role:</b> Anti-Corvette \n<b>Prerequisites:</b> Fighter Facility & Advanced Research Module \n<b>Strong vs:</b> Corvettes \n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nBasically a fighter with a Pulsar Cannon strapped to it, and a larger reactor to compensate.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_AttackBomber",
    RequiredResearch = "InstaAdvancedFighterTech",
    RequiredShipSubSystems = "FighterProduction | BCIonBeamTurret",
    DisplayPriority = 24,
    DisplayedName = "$7034",
    Description = "<b>Ship Class:</b> Fighter \n<b>Sub Class:</b> Bomber \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Fighter Facility & Research Module \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nSporting dual plasma projection arrays, the bomber, although slow, can bring down intense firepower onto a single slower moving target. Plasma Arrays can be upgraded.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_heavybomber",
    RequiredResearch = "InstaAdvancedFighterTech2",
    RequiredShipSubSystems = "FighterProduction | BCIonBeamTurret",
    DisplayPriority = 25,
    DisplayedName = "Heavy Bomber",
    Description = "<b>Ship Class:</b> Fighter \n<b>Sub Class:</b> Heavy Bomber \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Fighter Facility & Advanced Research Module \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nTaking the Attack Bomber design, strapping on some heavy kinetic cannons, and increasing the output of the plasma projection arrays, the bomber benefits from increased firepower and armor, but suffers from further decreased speed.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_AssaultCorvette",
    RequiredResearch = "",
    RequiredShipSubSystems = "CorvetteProduction | BCIonBeamTurret",
    DisplayPriority = 50,
    DisplayedName = "$7038",
    Description = "<b>Ship Class:</b> Corvette \n<b>Sub Class:</b> Light \n<b>Role:</b> Anti-Fighter \n<b>Prerequisites:</b> Corvette Facility \n<b>Strong vs:</b> Fighters \n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nArmed with two dual barreled rapid firing kinetic cannons, and above average speed, this corvette is an excellent anti-fighter corvette, although its light armor should see it used in a support role.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_PulsarCorvette",
    RequiredResearch = "",
    RequiredShipSubSystems = "CorvetteProduction | BCIonBeamTurret",
    DisplayPriority = 51,
    DisplayedName = "$7040",
    Description = "<b>Ship Class:</b> Corvette \n<b>Sub Class:</b> Light \n<b>Role:</b> Anti-Corvette \n<b>Prerequisites:</b> Corvette Facility \n<b>Strong vs:</b> Corvettes \n<b>Weak vs:</b> Fighters, Capital Ships \n\n<b>Description:</b> \nArmed with a heavy pulsar, excellent tracking system, and above average speed, this corvette is excellent at anti-corvette roles, although its light armor should see it used mainly in support.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_multiguncorvette",
    RequiredResearch = "InstaAdvancedFighterTech2",
    RequiredShipSubSystems = "CorvetteProduction | BCIonBeamTurret",
    DisplayPriority = 52,
    DisplayedName = "Multi-Gun Corvette",
    Description = "<b>Ship Class:</b> Corvette \n<b>Sub Class:</b> Medium \n<b>Role:</b> Anti-Fighter \n<b>Prerequisites:</b> Corvette Facility & Advanced Research Module \n<b>Strong vs:</b> Fighters \n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nArmed four dual barreled rapid fire kinetic turrets, and above average armor, this corvette is an excellent fighter suppression vessel.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_siegecorvette",
    RequiredResearch = "InstaAdvancedFighterTech2",
    RequiredShipSubSystems = "CorvetteProduction | BCIonBeamTurret",
    DisplayPriority = 53,
    DisplayedName = "Siege Corvette",
    Description = "<b>Ship Class:</b> Corvette \n<b>Sub Class:</b> Heavy \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Corvette Facility & Advanced Research Module \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nArmed with two dual barreled heavy plasma projection arrays, this corvette brings unimaginable destruction to anything it can brings its weapons to bear on. Heavily armored and sporting a dual tube light missile defense turret, this corvette can handle itself, but its slow speed should be paired with a faster moving escort",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_MinelayerCorvette",
    RequiredResearch = "GraviticAttractionMines",
    RequiredShipSubSystems = "CorvetteProduction | BCIonBeamTurret",
    DisplayPriority = 55,
    DisplayedName = "$7042",
    Description = "<b>Ship Class:</b> Corvette \n<b>Sub Class:</b> Medium \n<b>Role:</b> Area Denial \n<b>Prerequisites:</b> Corvette Facility & Minelayer Corvette Research \n<b>Strong vs:</b> N\A \n<b>Weak vs:</b> N\A \n\n<b>Description:</b> \nThis corvette is designed for one purpose: to drop mines.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_TorpedoFrigate",
    RequiredResearch = "",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 60,
    DisplayedName = "$7046",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Light \n<b>Role:</b> Anti-Frigate \n<b>Prerequisites:</b> Frigate Facility \n<b>Strong vs:</b> Frigates \n<b>Weak vs:</b> Fighters, Capital Ships \n\n<b>Description:</b> \nArmed with two heavy torpedo tubes (which can launch either heavy torpedos, or anti-strike craft cluster torpedos), and dual light missile defense turrets, this ship is most effective versus frigates, but can defend itself from light strike craft attack.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_AssaultFrigate",
    RequiredResearch = "",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 61,
    DisplayedName = "$7048",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Light \n<b>Role:</b> Anti-Strike Craft \n<b>Prerequisites:</b> Frigate Facility \n<b>Strong vs:</b> Fighters, Corvettes \n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nArmed with two dual barreled flak turrets, and few light hull defense weapons, this frigate is an effective rapid deployment anti-strike craft ship.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_GunFrigate",
    RequiredResearch = "InstaAdvancedFrigateTech",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 62,
    DisplayedName = "GunFrigate",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Light \n<b>Role:</b> Anti-Frigate \n<b>Prerequisites:</b> Frigate Facility & Advanced Research Module \n<b>Strong vs:</b> Frigates \n<b>Weak vs:</b> Capital Ships \n\n<b>Description:</b> \nRumored to be driven by fighter pilots after promotion, Gun Frigate captains are pretty much that. Armed with two heavy kinetic cannons, a spinal mounted plasma projection array, and a handful of hull defense weapons, this frigate is the defintion of old fashioned combat gone right.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_PulsarFrigate",
    RequiredResearch = "InstaAdvancedFrigateTech",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 63,
    DisplayedName = "Pulsar Frigate",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Medium \n<b>Role:</b> Anti-Corvette \n<b>Prerequisites:</b> Frigate Facility & Advanced Research Module & \n<b>Strong vs:</b> Fighters, Corvettes \n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nArmed with a dual barreled heavy pulsar cannon, a dual barreled medium pulsar cannon, a PDW missile launcher, and an advanced targeting sensor, this frigate excels at swatting corvettes from the sky.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_IonCannonFrigate",
    RequiredResearch = "InstaAdvancedFrigateTech",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 64,
    DisplayedName = "$7050",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Medium \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Frigate Facility & Advanced Research Module \n<b>Strong vs:</b> Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nArmed with a heavy spinally mounted ion cannon, and a light plasma cannon defense turret, this frigate is heavily armed, and armored, but its low manuverability, make it difficult at times to bring the weapon to bare on especially faster moving frigates, like the gun frigate.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_MissileFrigate",
    RequiredResearch = "InstaAdvancedFrigateTech",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 65,
    DisplayedName = "Long Range Missile Frigate",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Medium \n<b>Role:</b> Long Range Fire Support \n<b>Prerequisites:</b> Frigate Facility & Advanced Research Module \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nArmed with two long range torpedo tubes, and a light pulsar defense turret, this frigate can provide excellent fire support while staying fairly safe.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_PlasmaFrigate",
    RequiredResearch = "OverclockedFrigatePower",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 66,
    DisplayedName = "Plasma Projection Frigate",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Heavy \n<b>Role:</b> Anti-Frigate Superiority \n<b>Prerequisites:</b> Frigate Facility & Advanced Research Module & Plasma Projection Frigate Research \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nWeighted with a triple barreled spinally mounted heavy plasma projection array, dual heavy pulsating beam turrets, and 4 light plasma defense turrets, this frigate brings absurd firepower to the battle.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_MarineFrigate",
    RequiredResearch = "InstaAdvancedFrigateTech",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 67,
    DisplayedName = "$7052",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Medium \n<b>Role:</b> Capture Vessel \n<b>Prerequisites:</b> Frigate Facility & Advanced Research Module \n<b>Strong vs:</b> N\A \n<b>Weak vs:</b> N\A \n\n<b>Description:</b> \nCarrying elite Hiigaran Marines, and a prototype short range teleportation beam, this frigate can actually 'beam' boarding parties onto an enemy vessel to capture it.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_DefenseFieldFrigate",
    RequiredResearch = "DefenseFieldFrigateShield",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 68,
    DisplayedName = "$7044",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Medium \n<b>Role:</b> Fleet Defense \n<b>Prerequisites:</b> Frigate Facility & Advanced Research Module \n<b>Strong vs:</b> N\A \n<b>Weak vs:</b> N\A \n\n<b>Description:</b> \nUtilizing repulsor technology coupled with an electro-magnetic barrier system, the defense field frigate can actually negate, or destroy incoming fire for a short period of time.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_SupportFrigate",
    RequiredResearch = "InstaAdvancedFrigateTech",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 69,
    DisplayedName = "SupportFrigate",
    Description = "<b>Ship Class:</b> Frigate \n<b>Sub Class:</b> Medium \n<b>Role:</b> Fleet Repair \n<b>Prerequisites:</b> Frigate Facility & Advanced Research Module \n<b>Strong vs:</b> N\A \n<b>Weak vs:</b> N\A \n\n<b>Description:</b> \nCarrying Advanced Zero-G repair teams, and universal repair equipment this frigate can significantly multiply the rate at which ships within its area can repair themselves, subsystems, or even strike craft docked with them.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_lightcarrier",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 110,
    DisplayedName = "Light Carrier",
    Description = "<b>Ship Class:</b> Carrier \n<b>Sub Class:</b> Light \n<b>Role:</b> Rapid Deployment, and production \n<b>Prerequisites:</b> None \n<b>Strong vs:</b> N\A \n<b>Weak vs:</b> N\A \n\n<b>Description:</b> \nSmall, cheap and buildable in non-modulerized berths, this carrier can be built from second one, and is extremely useful in early game situations.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_Carrier",
    RequiredResearch = "",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 111,
    DisplayedName = "$7054",
    Description = "<b>Ship Class:</b> Carrier \n<b>Sub Class:</b> Standard \n<b>Role:</b> Production and forward combat operations. \n<b>Prerequisites:</b> Capital Ship Facility \n<b>Strong vs:</b> N\A \n<b>Weak vs:</b> N\A \n\n<b>Description:</b> \nCapable of building up to frigate sized ships, and bringing in shipyards. Although lightly armed, and armored, this ship is an excellent vessel to base, and maintain, a small strike force.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_Carrier_Bishop",
    RequiredResearch = "",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 112,
    DisplayedName = "Bishop Carrier",
    Description = "<b>Ship Class:</b> Carrier \n<b>Sub Class:</b> Engagement \n<b>Role:</b> Combat and Fleet Production. \n<b>Prerequisites:</b> Capital Ship Facility \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Armament:</b> \n4x8 Flash Rocket Launchers\n6x1 Hull Defense Points\n2x Light Turret Hardpoints\n\n<b>Description:</b> \nDesigned to be a cheap, rapidly built, and fast moving replacement to fully specalized carriers, the Bishop Carrier is a retrofitted transport built to provide effective fleet support specifically for fleets on the move in contested space.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_battleship",
    RequiredResearch = "BattleshipTech",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 113,
    DisplayedName = "Escort Destroyer",
    Description = "<b>Ship Class:</b> Destroyer \n<b>Role:</b> Escort \n<b>Prerequisites:</b> Capital Ship Facility & Escort Destroyer Research \n<b>Strong vs:</b> Fighters, Corvettes \n<b>Weak vs:</b> Capital Ships \n\n<b>Armament:</b>\n3x4 Rapid Flak Turrets\n2x2 Heavy Pulsar Turrets\n2x1 Railguns, Spinal Mount\n3x2 Light Missile Defense Turrets\n\n<b>Description:</b> \nThis ship is an excellent escort ship, although frequenlty outmatched by other capital ships, this ship is armed to provide support fire for the current battle.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_Destroyer",
    RequiredResearch = "DestroyerTech",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 114,
    DisplayedName = "$7056",
    Description = "<b>Ship Class:</b> Destroyer \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Capital Ship Facility & Destroyer Research \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Armament:</b> \n3x2 Heavy Kinetic Turrets \n2x2 Ion Cannon Turrets \n2x1 Torpedo Tubes \n3x2 Light kinetic Turrets \n\n<b>Description:</b> \nCapable of standing its on versus capital ships, and excelling against frigates, this ship does lack an effective Anti-Stike Craft armament, and should be escorted.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_lrDestroyer",
    RequiredResearch = "LrDestroyerTech",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 115,
    DisplayedName = "Support Destroyer",
    Description = "<b>Ship Class:</b> Destroyer \n<b>Role:</b> Long Range Fire Support \n<b>Prerequisites:</b> Capital Ship Facility & Support Destroyer Research \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Armament:</b> \n4x2 Long Range Railgun Turrets \n4x1 Cluster Torpedo Tubes \n\n<b>Description:</b> \nCapable of bringing intense firepower to bear over extensive distances, this is an extremely useful support fire vessel, but due to its slow turning turrets, it should be keep from close range combat as much as possible.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_Shipyard",
    RequiredResearch = "",
    RequiredShipSubSystems = "Hyperspace",
    DisplayPriority = 116,
    DisplayedName = "$7058",
    Description = "$7059",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_lightcruiser",
    RequiredResearch = "AssaultCarrierProductionFacilitys",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 117,
    DisplayedName = "Light Cruiser",
    Description = "<b>Ship Class:</b> Light Cruiser \n<b>Role:</b> Anti-Frigate \n<b>Prerequisites:</b> Capital Ship Facility & Light Cruiser Research \n<b>Strong vs:</b> Frigates \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Armament:</b> \n1x Ion Cannon Turret \n1x Heavy Pulsar Turret \n12x heavy Rocket Tubes \n2x Pulsar Defense Turrets \n8x Light Plasma Defense Turrets \n8x Hull Defense Points \n\n<b>Description:</b> \nHaving its firepower spread over so many arcs, this ship frequently falls short in the capital ship fight, but excels in taking down groups of enemy frigates while effectively fending off enemy strike craft.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_cruiser",
    RequiredResearch = "AssaultCarrierProductionFacilitys",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 118,
    DisplayedName = "Cruiser",
    Description = "<b>Ship Class:</b> Light Cruiser \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Capital Ship Facility & Light Cruiser Research \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Armament:</b> \n2x3 Mass Kinetic Turrets \n4x3 Heavy Kinetic Turrets \n2x2 Heavy Kinetic Turrets \n12x Torpedo Tubes \n1x2 Flak Turret \n6x1 Pulsating Beam Defense Points \n\n<b>Description:</b> \nHighly effective against frigates and capital ships this ship, while possessing an effective point defense armament, is still suseptable to large groups of hostile strike craft.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_Battlecruiser",
    RequiredResearch = "BattlecruiserIonWeapons",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 121,
    DisplayedName = "$7060",
    Description = "<b>Ship Class:</b> Battle Cruiser \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Capital Ship Facility & Heavy Cruiser Research \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Armament:</b> \n2x2 Very Heavy Ion Cannon Turrets \n4x3 Heavy Kinetic Turrets \n2x2 Heavy Kinetic Turrets \n3x2 Ultra Heavy Kinetic Turrets \n2x6 Heavy Torpedo Tubes \n6x1 Light Plasma Defense Turrets \n2x2 Pulsating Beam Defense Turrets \n4x1 Pulsating Beam Defense Points \n\n<b>Description:</b> \nThe ultimate Hiigaran Anti-Capital Ship available, should be escorted. Can build modules that add weapon systems, making it nearly on-par to a Battleship.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_GunTurret",
    RequiredResearch = "",
    RequiredShipSubSystems = "PlatformProduction",
    DisplayPriority = 149,
    DisplayedName = "$7062",
    Description = "<b>Ship Class:</b> Platform \n<b>Role:</b> Anti-Fighter \n<b>Prerequisites:</b> Platform Production Module \n<b>Strong vs:</b> Fighters\n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nArmed with two rapid flak turrets, this platform is an effective anti-fighter defense.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_PulsarTurret",
    RequiredResearch = "",
    RequiredShipSubSystems = "PlatformProduction",
    DisplayPriority = 150,
    DisplayedName = "Pulsar Turret",
    Description = "<b>Ship Class:</b> Platform \n<b>Role:</b> Anti-Corvette \n<b>Prerequisites:</b> Platform Production Module \n<b>Strong vs:</b> Corvettes \n<b>Weak vs:</b> Frigates, Capital Ships \n\n<b>Description:</b> \nArmed with two heavy pulsar turret, this platform is an effective anti-corvette defense.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_IonTurret",
    RequiredResearch = "PlatformIonWeapons",
    RequiredShipSubSystems = "PlatformProduction",
    DisplayPriority = 151,
    DisplayedName = "$7064",
    Description = "<b>Ship Class:</b> Platform \n<b>Role:</b> Anti-Capital Ship \n<b>Prerequisites:</b> Platform Production Module \n<b>Strong vs:</b> Frigates, Capital Ships \n<b>Weak vs:</b> Fighters, Corvettes \n\n<b>Description:</b> \nArmed with two light ion cannon turrets, this platform is an effective anti-frigate, and capital ship defense.",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_ResourceCollector",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 152,
    DisplayedName = "$7066",
    Description = "$7067",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_ResourceController",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 153,
    DisplayedName = "$7068",
    Description = "$7069",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_Probe",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 154,
    DisplayedName = "$7070",
    Description = "$7071",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_ProximitySensor",
    RequiredResearch = "SensDisProbe",
    RequiredShipSubSystems = "",
    DisplayPriority = 155,
    DisplayedName = "$7072",
    Description = "$7073",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_ECMProbe",
    RequiredResearch = "ECMProbe",
    RequiredShipSubSystems = "",
    DisplayPriority = 156,
    DisplayedName = "$7074",
    Description = "$7075",
  },
  {
    Type = Ship,
    ThingToBuild = "Hgn_Shipyard_SPG",
    RequiredResearch = "",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 157,
    DisplayedName = "$7058",
    Description = "$7059",
  },

  {
    Type = SubSystem,
    ThingToBuild = "hgn_bc_tubes",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 159,
    DisplayedName = "Mass Torpedo Tubes",
    Description = "<b>Barrel #:</b> 4 \n<b>Type:</b> Kiloton Torpedo \n<b>Damage:</b> 4500 \n<b>Burst Damage:</b> 3000-4500 \n<b>Burst Radius:</b> 200 \n<b>Range:</b> 7500 \n<b>Reload:</b> 30 \n<b>Firing Arc:</b> 360",
  },
  {
    Type = SubSystem,
    ThingToBuild = "hgn_bc_siege",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 160,
    DisplayedName = "Spinal Siege Cannons",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Siege Cannon \n<b>Damage:</b> 10000 \n<b>Burst Damage:</b> 2500-3000 \n<b>Burst Radius:</b> 150 \n<b>Range:</b> 8000 \n<b>Reload:</b> 15 \n<b>Firing Arc:</b> 6",
  },
  {
    Type = SubSystem,
    ThingToBuild = "hgn_bc_PDSArray",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 161,
    DisplayedName = "Additional Point Defense",
    Description = "<b>Additional Armaments:</b>\n8x1 Light Pulsar defense turrets \n2x1 Medium Pulsar defense turrets",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bwm_Kinetic",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 165,
    DisplayedName = "Tri-Barreled Kinetic Turret",
    Description = "<b>Barrel #:</b> 3 \n<b>Type:</b> Heavy Kinetic \n<b>Damage:</b> 700-750 \n<b>Range:</b> 6000 \n<b>Reload:</b> 6",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bwm_Kinetic2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 166,
    DisplayedName = "Tri-Barreled Kinetic Turret",
    Description = "<b>Barrel #:</b> 3 \n<b>Type:</b> Heavy Kinetic \n<b>Damage:</b> 700-750 \n<b>Range:</b> 6000 \n<b>Reload:</b> 6",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bwm_Artillery",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 167,
    DisplayedName = "Ultra Heavy Kinetic Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Ultra Heavy Kinetic \n<b>Damage:</b> 1500-1800 \n<b>Range:</b> 9000 \n<b>Reload:</b> 10",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bwm_Artillery2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 168,
    DisplayedName = "Ultra Heavy Kinetic Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Ultra Heavy Kinetic \n<b>Damage:</b> 1500-1800 \n<b>Range:</b> 9000 \n<b>Reload:</b> 10",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bwm_plasma",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 169,
    DisplayedName = "Heavy Plasma Bomb Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Heavy Plasma \n<b>Damage:</b> 2000-2500 \n<b>Range:</b> 6000 \n<b>Reload:</b> 6",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bwm_plasma2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 170,
    DisplayedName = "Heavy Plasma Bomb Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Heavy Plasma \n<b>Damage:</b> 2000-2500 \n<b>Range:</b> 6000 \n<b>Reload:</b> 6",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bwm_railgun",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 171,
    DisplayedName = "Rail-Gun Kinetic Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Railgun \n<b>Damage:</b> 2500-2750 \n<b>Range:</b> 9000 \n<b>Reload:</b> 8",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bwm_railgun2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 172,
    DisplayedName = "Rail-Gun Kinetic Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Railgun \n<b>Damage:</b> 2500-2750 \n<b>Range:</b> 9000 \n<b>Reload:</b> 8",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bwm_RapidFlak",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 173,
    DisplayedName = "Quad-Barreled Rapid Flak Turret",
    Description = "<b>Barrel #:</b> 4 \n<b>Type:</b> Flak \n<b>Damage:</b> 30 \n<b>Burst Damage:</b> 20-50 \n<b>Burst Radius:</b> 40 \n<b>Range:</b> 5000 \n<b>Reload:</b> 1",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bwm_RapidFlak2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 174,
    DisplayedName = "Quad-Barreled Rapid Flak Turret",
    Description = "<b>Barrel #:</b> 4 \n<b>Type:</b> Flak \n<b>Damage:</b> 30 \n<b>Burst Damage:</b> 20-50 \n<b>Burst Radius:</b> 40 \n<b>Range:</b> 5000 \n<b>Reload:</b> 1",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bwm_Torpedo",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 175,
    DisplayedName = "Turreted Missile Launcher",
    Description = "<b>Barrel #:</b> 6 \n<b>Type:</b> Torpedo \n<b>Damage:</b> 1000-2000 \n<b>Burst Damage:</b> 750-1000 \n<b>Burst Radius:</b> 120 \n<b>Range:</b> 6000 \n<b>Reload:</b> 30",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bwm_Torpedo2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 176,
    DisplayedName = "Turreted Missile Launcher",
    Description = "<b>Barrel #:</b> 6 \n<b>Type:</b> Torpedo \n<b>Damage:</b> 1000-2000 \n<b>Burst Damage:</b> 750-1000 \n<b>Burst Radius:</b> 120 \n<b>Range:</b> 6000 \n<b>Reload:</b> 30",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bpd_kinetic",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 177,
    DisplayedName = "Kinetic Point Defense Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Light Kinetic \n<b>Damage:</b> 21 \n<b>Range:</b> 3400 \n<b>Reload:</b> 0.5",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bpd_kinetic2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 178,
    DisplayedName = "Kinetic Point Defense Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Light Kinetic \n<b>Damage:</b> 21 \n<b>Range:</b> 3400 \n<b>Reload:</b> 0.5",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bpd_missile",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 179,
    DisplayedName = "Light Missile Defense Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Light Missile \n<b>Damage:</b> 100 \n<b>Burst Damage:</b> 50-150 \n<b>Range:</b> 5000 \n<b>Reload:</b> 4",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bpd_missile2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 180,
    DisplayedName = "Light Missile Defense Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Light Missile \n<b>Damage:</b> 100 \n<b>Burst Damage:</b> 50-150 \n<b>Range:</b> 5000 \n<b>Reload:</b> 4",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bpd_flak",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 181,
    DisplayedName = "Light Flak Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Flak \n<b>Damage:</b> 30 \n<b>Burst Damage:</b> 20-50 \n<b>Range:</b> 5000 \n<b>Reload:</b> 1",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bpd_flak2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 182,
    DisplayedName = "Light Flak Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Flak \n<b>Damage:</b> 30 \n<b>Burst Damage:</b> 20-50 \n<b>Range:</b> 5000 \n<b>Reload:</b> 1",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bpd_energy",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 183,
    DisplayedName = "Plasma Bolt Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Light Plasma \n<b>Damage:</b> 30-45 \n<b>Range:</b> 3750 \n<b>Burst of:</b> 12 \n<b>Every:</b> 4.5 seconds",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bpd_energy2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 184,
    DisplayedName = "Plasma Bolt Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Light Plasma \n<b>Damage:</b> 30-45 \n<b>Range:</b> 3750 \n<b>Burst of:</b> 12 \n<b>Every:</b> 4.5 seconds",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bpd_pulsar",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 185,
    DisplayedName = "Rapid Pulsar Defense Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Rapid Pulsar \n<b>Damage:</b> 50-75 \n<b>Range:</b> 3750 \n<b>Burst of:</b> 6 \n<b>Every:</b> 3.5 seconds",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Hgn_bpd_pulsar2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | AdvancedResearch",
    DisplayPriority = 186,
    DisplayedName = "Rapid Pulsar Defense Turret",
    Description = "<b>Barrel #:</b> 2 \n<b>Type:</b> Rapid Pulsar \n<b>Damage:</b> 50-75 \n<b>Range:</b> 3750 \n<b>Burst of:</b> 6 \n<b>Every:</b> 3.5 seconds",
  },
}