Icon_Speed = "data:ui/newui/research/icons/speed.mres"
Icon_Health = "data:ui/newui/research/icons/health.mres"
Icon_Tech = "data:ui/newui/research/icons/tech.mres"
Icon_Ability = "data:ui/newui/research/icons/ability.mres"
Icon_Build = "data:ui/newui/research/icons/build.mres"
Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2
research = {
  {
    Name = "ImprovedTorpedo",
    RequiredResearch = "AttackBomberEliteWeaponUpgrade",
    RequiredSubSystems = "Hgn_MS_Production_CorvetteMover",
    Cost = 1,
    Time = 1,
    DisplayedName = "Ignore me",
    DisplayPriority = 1,
    Description = "Added in to provide a form of stfu for the games sad sad ai scripting.",
    TargetName = "Hgn_Mothership",
  },
  {
    Name = "InstaAdvancedFrigateTech",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "Hgn_Mothership",
  },
  {
    Name = "InstaAdvancedFighterTech",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "Hgn_Mothership",
  },
  {
    Name = "InstaAdvancedFighterTech2",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "Hgn_Mothership",
  },
  {
    Name = "GraviticAttractionMines",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 750,
    Time = 40,
    DisplayedName = "$7500",
    DisplayPriority = 2,
    Description = "$7501",
    TargetName = "Hgn_MinelayerCorvette",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7200",
  },
  {
    Name = "PlatformIonWeapons",
    Required = "",
    RequiredSubSystems = "Research | AdvancedResearch & PlatformProduction",
    Cost = 400,
    Time = 30,
    DisplayedName = "$7502",
    DisplayPriority = 24,
    Description = "$7503",
    TargetName = "Hgn_IonTurret",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7201",
  },
  {
    Name = "BattleshipTech",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 700,
    Time = 80,
    DisplayedName = "Destroyer Class Chassis",
    DisplayPriority = 3,
    Description = "<b>Description:</b> Unlocks Escort Destroyers. \n\n<b>Prerequisites:</b> Research Module and Capital Ship Facility.",
    TargetName = "Hgn_Battleship",
    Icon = Icon_Tech,
    ShortDisplayedName = "Escort Destroyer",
  },
  {
    Name = "DestroyerTech",
    RequiredResearch = "BattleshipTech",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 1250,
    Time = 100,
    DisplayedName = "Turreted Ion Cannon",
    DisplayPriority = 3,
    Description = "<b>Description:</b> Unlocks Destroyers. \n\n<b>Prerequisites:</b> Research Module, Capital Ship Facility, and Destroyer Class Chassis research.",
    TargetName = "Hgn_Destroyer",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7203",
  },
  {
    Name = "LrDestroyerTech",
    RequiredResearch = "BattleshipTech",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 1400,
    Time = 120,
    DisplayedName = "Turreted Railgun",
    DisplayPriority = 3,
    Description = "<b>Description:</b> Unlocks Support Destroyer. \n\n<b>Prerequisites:</b> Advanced Research Module, Capital Ship Facility, and Destroyer class chassis research.",
    TargetName = "Hgn_lrdestroyer",
    Icon = Icon_Tech,
    ShortDisplayedName = "Support Destroyer",
  },
  {
    Name = "AssaultCarrierProductionFacilitys",
    RequiredResearch = "DestroyerTech",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 1400,
    Time = 140,
    DisplayedName = "Small Cruiser Chassis",
    DisplayPriority = 1,
    Description = "<b>Description:</b> Unlocks Cruiser, and Light Cruiser. \n\n<b>Prerequisites:</b> Research Module, Capital Ship Facility, and . ",
    TargetName = "Hgn_Cruiser",
    Icon = Icon_Tech,
    ShortDisplayedName = "Small Cruiser Chassis",
  },
  {
    Name = "BattlecruiserIonWeapons",
    RequiredResearch = "AssaultCarrierProductionFacilitys",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 2800,
    Time = 200,
    DisplayedName = "Heavy Cruiser chassis",
    DisplayPriority = 1,
    Description = "<b>Description:</b> Unlocks Battle Cruiser which can only be built from shipyards. \n\n<b>Prerequisites:</b> Advanced Research Module, Capital Ship Facility, and Small Cruiser Chassis research.",
    TargetName = "Hgn_BattleCruiser",
    Icon = Icon_Tech,
    ShortDisplayedName = "Heavy Cruiser Chassis",
  },
  {
    Name = "ECMProbe",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 500,
    Time = 45,
    DisplayedName = "$7509",
    DisplayPriority = 4,
    Description = "$7510",
    TargetName = "Hgn_ECMProbe",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7204",
  },
  {
    Name = "SensDisProbe",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 500,
    Time = 35,
    DisplayedName = "$7650",
    DisplayPriority = 5,
    Description = "$7651",
    TargetName = "Hgn_ProximitySensor",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7214",
  },
  {
    Name = "OverclockedFrigatePower",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 700,
    Time = 60,
    DisplayedName = "Ultra-High Output Frigate Powerplant",
    DisplayPriority = 7,
    Description = "<b>Description:</b> Unlocks Plasma Frigates. \n\n<b>Prerequisites:</b> Advanced Research Module.",
    TargetName = "Hgn_PlasmaFrigate",
    Icon = Icon_Tech,
    ShortDisplayedName = "Plasma Frigate",
  },
  {
    Name = "DamageMoverTech",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 400,
    Time = 60,
    DisplayedName = "$7900",
    DisplayPriority = 29,
    Description = "$7901",
    TargetName = "Hgn_Mothership",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7902",
  },
  {
    Name = "RadiationDefenseField",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 400,
    Time = 60,
    DisplayedName = "$7905",
    DisplayPriority = 30,
    Description = "$7906",
    UpgradeType = Ability,
    TargetType = Ship,
    UpgradeName = "DefenseFieldShield",
    TargetName = "Hgn_DefenseFieldFrigate",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7907",
  },
  {
    Name = "RepairAbility",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 500,
    Time = 40,
    DisplayedName = "$7511",
    DisplayPriority = 26,
    Description = "$7512",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Hgn_ResourceCollector",
    UpgradeName = "Repair",
    Icon = Icon_Ability,
    ShortDisplayedName = "$7205",
  },
  {
    Name = "ScoutPingAbility",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 400,
    Time = 40,
    DisplayedName = "$7513",
    DisplayPriority = 27,
    Description = "$7514",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Hgn_Scout",
    UpgradeName = "SensorPing",
    Icon = Icon_Ability,
    ShortDisplayedName = "$7206",
  },
  {
    Name = "AttackBomberImprovedBombs",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 1000,
    Time = 45,
    DisplayedName = "$7517",
    DisplayPriority = 30,
    Description = "$7518",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Hgn_AttackBomber",
    UpgradeName = "UseSpecialWeaponsInNormalAttack",
    Icon = Icon_Ability,
    ShortDisplayedName = "$7208",
  },
  {
    Name = "ScoutEMPAbility",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 1500,
    Time = 60,
    DisplayedName = "$7519",
    DisplayPriority = 31,
    Description = "$7520",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Hgn_Scout",
    UpgradeName = "SpecialAttack",
    Icon = Icon_Ability,
    ShortDisplayedName = "$7209",
  },
  {
    Name = "DefenseFieldFrigateShield",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 1250,
    Time = 60,
    DisplayedName = "$7521",
    DisplayPriority = 32,
    Description = "$7522",
    TargetName = "Hgn_DefenseFieldFrigate",
    Icon = Icon_Ability,
    ShortDisplayedName = "$7210",
  },
  {
    Name = "MothershipHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 200,
    Time = 15,
    DisplayedName = "$7523",
    DisplayPriority = 41,
    Description = "$7524",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.5,
    Icon = Icon_Health,
    ShortDisplayedName = "$7211",
  },
  {
    Name = "MothershipHealthUpgrade2",
    RequiredResearch = "MothershipHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 265,
    Time = 20,
    DisplayedName = "$7525",
    DisplayPriority = 41,
    Description = "$7526",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 2,
    Icon = Icon_Health,
    ShortDisplayedName = "$7212",
  },
  {
    Name = "MothershipMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 200,
    Time = 15,
    DisplayedName = "$7527",
    DisplayPriority = 44,
    Description = "$7528",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7211",
  },
  {
    Name = "MothershipMAXSPEEDUpgrade2",
    RequiredResearch = "MothershipMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 265,
    Time = 20,
    DisplayedName = "$7529",
    DisplayPriority = 44,
    Description = "$7530",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7212",
  },
  {
    Name = "MothershipBUILDSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 800,
    Time = 60,
    DisplayedName = "$7800",
    DisplayPriority = 45,
    Description = "$7801",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "BUILDSPEED",
    UpgradeValue = 1.3,
    Icon = Icon_Build,
    ShortDisplayedName = "$7240",
  },
  {
    Name = "CarrierHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 200,
    Time = 20,
    DisplayedName = "$7531",
    DisplayPriority = 61,
    Description = "$7532",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7221",
  },
  {
    Name = "CarrierHealthUpgrade2",
    RequiredResearch = "CarrierHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 350,
    Time = 30,
    DisplayedName = "$7533",
    DisplayPriority = 61,
    Description = "$7534",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7222",
  },
  {
    Name = "CarrierMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 200,
    Time = 15,
    DisplayedName = "$7535",
    DisplayPriority = 64,
    Description = "$7536",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7221",
  },
  {
    Name = "CarrierMAXSPEEDUpgrade2",
    RequiredResearch = "CarrierMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 350,
    Time = 20,
    DisplayedName = "$7537",
    DisplayPriority = 64,
    Description = "$7538",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7222",
  },
  {
    Name = "CarrierBUILDSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 1100,
    Time = 60,
    DisplayedName = "$7805",
    DisplayPriority = 65,
    Description = "$7806",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier",
    UpgradeName = "BUILDSPEED",
    UpgradeValue = 1.3,
    Icon = Icon_Build,
    ShortDisplayedName = "$7240",
  },
  {
    Name = "LightCarrierHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 200,
    Time = 20,
    DisplayedName = "Light Carrier Armor 1",
    DisplayPriority = 66,
    Description = "<b>Description:</b> Improves Light Carrier max health. \n\n<b>Prerequisites:</b> Research Module.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_LightCarrier",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 1 Light Carrier",
  },
  {
    Name = "LightCarrierHealthUpgrade2",
    RequiredResearch = "LightCarrierHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 350,
    Time = 30,
    DisplayedName = "Light Carrier Armor 2",
    DisplayPriority = 66,
    Description = "<b>Description:</b> Improves Light Carrier max health to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_LightCarrier",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 2 Light Carrier",
  },
  {
    Name = "LightCarrierMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 200,
    Time = 15,
    DisplayedName = "Light Carrier Engine 1",
    DisplayPriority = 67,
    Description = "<b>Description:</b> Improves Light Carrier max speed. \n\n<b>Prerequisites:</b> Research Module.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_LightCarrier",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 Light Carrier",
  },
  {
    Name = "LightCarrierMAXSPEEDUpgrade2",
    RequiredResearch = "LightCarrierMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 350,
    Time = 20,
    DisplayedName = "Light Carrier Engine 2",
    DisplayPriority = 67,
    Description = "<b>Description:</b> Improves Light Carrier max speed to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_LightCarrier",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 Light Carrier",
  },
  {
    Name = "LightCarrierBUILDSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 1100,
    Time = 60,
    DisplayedName = "Improved Manufacturing",
    DisplayPriority = 68,
    Description = "<b>Description:</b> Improves construction speed by 30% on all Light Carriers. \n\n<b>Prerequisites:</b> Advanced Research Module.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_LightCarrier",
    UpgradeName = "BUILDSPEED",
    UpgradeValue = 1.3,
    Icon = Icon_Build,
    ShortDisplayedName = "Imp. Manufacturing",
  },
  {
    Name = "Carrier_187HealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 200,
    Time = 20,
    DisplayedName = "Carrier Armor 1",
    DisplayPriority = 69,
    Description = "<b>Description:</b> Improves Carrier max health. \n\n<b>Prerequisites:</b> Research Module.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier_187",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 1 Carrier",
  },
  {
    Name = "Carrier_187HealthUpgrade2",
    RequiredResearch = "Carrier_187HealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 350,
    Time = 30,
    DisplayedName = "Carrier Armor 2",
    DisplayPriority = 69,
    Description = "<b>Description:</b> Improves Carrier max health to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier_187",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 2 Carrier",
  },
  {
    Name = "Carrier_187MAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 200,
    Time = 15,
    DisplayedName = "Carrier Engine 1",
    DisplayPriority = 70,
    Description = "<b>Description:</b> Improves Carrier max speed. \n\n<b>Prerequisites:</b> Research Module.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier_187",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 Carrier",
  },
  {
    Name = "Carrier_187MAXSPEEDUpgrade2",
    RequiredResearch = "Carrier_187MAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 350,
    Time = 20,
    DisplayedName = "Carrier Engine 2",
    DisplayPriority = 70,
    Description = "<b>Description:</b> Improves Carrier max speed to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier_187",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 Carrier",
  },
  {
    Name = "Carrier_187BUILDSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 1100,
    Time = 60,
    DisplayedName = "Improved Manufacturing",
    DisplayPriority = 71,
    Description = "<b>Description:</b> Improves construction speed by 30% on all Carriers. \n\n<b>Prerequisites:</b> Advanced Research Module.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier_187",
    UpgradeName = "BUILDSPEED",
    UpgradeValue = 1.3,
    Icon = Icon_Build,
    ShortDisplayedName = "Imp. Manufacturing",
  },
  {
    Name = "BishopCarrierHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & CrewSuite",
    Cost = 150,
    Time = 10,
    DisplayedName = "Bishop Carrier Armor 1",
    DisplayPriority = 72,
    Description = "<b>Description:</b> Improves Bishop Carrier max health. \n\n<b>Prerequisites:</b> Expert Crew Module.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier_Bishop",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 1 Bishop Carrier",
  },
  {
    Name = "BishopCarrierHealthUpgrade2",
    RequiredResearch = "BishopCarrierHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CrewSuite",
    Cost = 200,
    Time = 15,
    DisplayedName = "Bishop Carrier Armor 2",
    DisplayPriority = 72,
    Description = "<b>Description:</b> Improves Bishop Carrier max health to Lvl 2. \n\n<b>Prerequisites:</b> Expert Crew Module.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier_Bishop",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 2 Bishop Carrier",
  },
  {
    Name = "BishopCarrierMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & CrewSuite",
    Cost = 100,
    Time = 5,
    DisplayedName = "Bishop Carrier Engine 1",
    DisplayPriority = 73,
    Description = "<b>Description:</b> Improves Bishop Carrier max speed. \n\n<b>Prerequisites:</b> Expert Crew Module.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier_Bishop",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 Bishop Carrier",
  },
  {
    Name = "BishopCarrierMAXSPEEDUpgrade2",
    RequiredResearch = "BishopCarrierMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CrewSuite",
    Cost = 150,
    Time = 10,
    DisplayedName = "Bishop Carrier Engine 2",
    DisplayPriority = 73,
    Description = "<b>Description:</b> Improves Bishop Carrier max speed to Lvl 2. \n\n<b>Prerequisites:</b> Expert Crew Module.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier_Bishop",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 Bishop Carrier",
  },
  {
    Name = "InterceptorMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
    Cost = 125,
    Time = 15,
    DisplayedName = "$7543",
    DisplayPriority = 81,
    Description = "$7544",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Interceptor",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.25,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7231",
  },
  {
    Name = "InterceptorMAXSPEEDUpgrade2",
    RequiredResearch = "InterceptorMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FighterProduction",
    Cost = 175,
    Time = 20,
    DisplayedName = "$7545",
    DisplayPriority = 81,
    Description = "$7546",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Interceptor",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.5,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7232",
  },
  {
    Name = "HeavyFighterMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & FighterProduction",
    Cost = 125,
    Time = 15,
    DisplayedName = "HeavyFighter Engine 1",
    DisplayPriority = 82,
    Description = "<b>Description:</b> Improves Heavy Fighter max speed. \n\n<b>Prerequisites:</b> Advanced Research Module and Fighter Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_HeavyFighter",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.25,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 HeavyFighter",
  },
  {
    Name = "HeavyFighterMAXSPEEDUpgrade2",
    RequiredResearch = "HeavyFighterMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FighterProduction",
    Cost = 175,
    Time = 20,
    DisplayedName = "HeavyFighter Engine 2",
    DisplayPriority = 82,
    Description = "<b>Description:</b> Improves Heavy Fighter max speed to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Fighter Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_HeavyFighter",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.5,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 HeavyFighter",
  },
  {
    Name = "StrikeFighterMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & FighterProduction",
    Cost = 125,
    Time = 15,
    DisplayedName = "StrikeFighter Engine 1",
    DisplayPriority = 82,
    Description = "<b>Description:</b> Improves Strike Fighter max speed. \n\n<b>Prerequisites:</b> Advanced Research Module and Fighter Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_StrikeFighter",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.25,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 StrikeFighter",
  },
  {
    Name = "StrikeFighterMAXSPEEDUpgrade2",
    RequiredResearch = "strikeFighterMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FighterProduction",
    Cost = 175,
    Time = 20,
    DisplayedName = "StrikeFighter Engine 2",
    DisplayPriority = 82,
    Description = "<b>Description:</b> Improves Strike Fighter max speed to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Fighter Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_StrikeFighter",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.5,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 StrikeFighter",
  },
  {
    Name = "BeamFighterMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & FighterProduction",
    Cost = 125,
    Time = 15,
    DisplayedName = "PulsarFighter Engine 1",
    DisplayPriority = 82,
    Description = "<b>Description:</b> Improves Pulsar Fighter max speed. \n\n<b>Prerequisites:</b> Advanced Research Module and Fighter Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_BeamFighter",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.25,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 PulsarFighter",
  },
  {
    Name = "BeamFighterMAXSPEEDUpgrade2",
    RequiredResearch = "BeamFighterMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FighterProduction",
    Cost = 175,
    Time = 20,
    DisplayedName = "PulsarFighter Engine 2",
    DisplayPriority = 82,
    Description = "<b>Description:</b> Improves Pulsar Fighter max speed to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Fighter Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_BeamFighter",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.5,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 PulsarFighter",
  },
  {
    Name = "AttackBomberMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
    Cost = 125,
    Time = 15,
    DisplayedName = "$7551",
    DisplayPriority = 87,
    Description = "$7552",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AttackBomber",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.25,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7234",
  },
  {
    Name = "AttackBomberMAXSPEEDUpgrade2",
    RequiredResearch = "AttackBomberMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FighterProduction",
    Cost = 175,
    Time = 20,
    DisplayedName = "$7553",
    DisplayPriority = 87,
    Description = "$7554",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AttackBomber",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.5,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7235",
  },
  {
    Name = "HeavyBomberMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & FighterProduction",
    Cost = 125,
    Time = 15,
    DisplayedName = "Heavy Bomber Engine 1",
    DisplayPriority = 88,
    Description = "<b>Description:</b> Improves Heavy Bomber max speed. \n\n<b>Prerequisites:</b> Advanced Research Module and Fighter Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_HeavyBomber",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.25,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 Heavy Bomber",
  },
  {
    Name = "HeavyBomberMAXSPEEDUpgrade2",
    RequiredResearch = "HeavyBomberMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FighterProduction",
    Cost = 175,
    Time = 20,
    DisplayedName = "Heavy Bomber Engine 2",
    DisplayPriority = 88,
    Description = "<b>Description:</b> Improves Heavy Bomber max speed to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Fighter Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_HeavyBomber",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.5,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 Heavy Bomber",
  },
  {
    Name = "AssaultCorvetteHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
    Cost = 200,
    Time = 20,
    DisplayedName = "$7555",
    DisplayPriority = 200,
    Description = "$7556",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultCorvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7237",
  },
  {
    Name = "AssaultCorvetteHealthUpgrade2",
    RequiredResearch = "AssaultCorvetteHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 225,
    Time = 25,
    DisplayedName = "$7557",
    DisplayPriority = 200,
    Description = "$7558",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultCorvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7238",
  },
  {
    Name = "AssaultCorvetteMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
    Cost = 225,
    Time = 20,
    DisplayedName = "$7559",
    DisplayPriority = 203,
    Description = "$7560",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultCorvette",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7237",
  },
  {
    Name = "AssaultCorvetteMAXSPEEDUpgrade2",
    RequiredResearch = "AssaultCorvetteMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 200,
    Time = 25,
    DisplayedName = "$7561",
    DisplayPriority = 203,
    Description = "$7562",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultCorvette",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7238",
  },
  {
    Name = "PulsarCorvetteHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
    Cost = 150,
    Time = 20,
    DisplayedName = "$7563",
    DisplayPriority = 206,
    Description = "$7564",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_PulsarCorvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7241",
  },
  {
    Name = "PulsarCorvetteHealthUpgrade2",
    RequiredResearch = "PulsarCorvetteHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 225,
    Time = 25,
    DisplayedName = "$7565",
    DisplayPriority = 206,
    Description = "$7566",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_PulsarCorvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7242",
  },
  {
    Name = "PulsarCorvetteMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
    Cost = 125,
    Time = 20,
    DisplayedName = "$7567",
    DisplayPriority = 209,
    Description = "$7568",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_PulsarCorvette",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7241",
  },
  {
    Name = "PulsarCorvetteMAXSPEEDUpgrade2",
    RequiredResearch = "PulsarCorvetteMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 225,
    Time = 25,
    DisplayedName = "$7569",
    DisplayPriority = 209,
    Description = "$7570",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_PulsarCorvette",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7242",
  },
  {
    Name = "multiguncorvetteHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 150,
    Time = 20,
    DisplayedName = "Multi-Gun Corvette Armor 1",
    DisplayPriority = 210,
    Description = "<b>Description:</b> Improves Multi-Gun Corvette max speed. \n\n<b>Prerequisites:</b> Advanced Research Module and Fighter Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_multiguncorvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 1 Multi-Gun Corvette",
  },
  {
    Name = "multiguncorvetteHealthUpgrade2",
    RequiredResearch = "multiguncorvetteHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 225,
    Time = 25,
    DisplayedName = "Multi-Gun Corvette Armor 2",
    Description = "<b>Description:</b> Improves Multi-Gun Corvette max speed to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Fighter Facility.",
    DisplayPriority = 210,
    Description = "$7566",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_multiguncorvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 2 Multi-Gun Corvette",
  },
  {
    Name = "multiguncorvetteMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 125,
    Time = 20,
    DisplayedName = "Multi-Gun Corvette Engine 1",
    DisplayPriority = 211,
    Description = "<b>Description:</b> Improves Multi-Gun Corvette max health. \n\n<b>Prerequisites:</b> Advanced Research Module and Fighter Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_multiguncorvette",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 Multi-Gun Corvette",
  },
  {
    Name = "multiguncorvetteMAXSPEEDUpgrade2",
    RequiredResearch = "multiguncorvetteMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 225,
    Time = 25,
    DisplayedName = "Multi-Gun Corvette Engine 2",
    DisplayPriority = 211,
    Description = "<b>Description:</b> Improves Multi-Gun Corvette max health to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Fighter Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_multiguncorvette",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 Multi-Gun Corvette",
  },
  {
    Name = "siegecorvetteHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 150,
    Time = 20,
    DisplayedName = "Siege Corvette Armor 1",
    DisplayPriority = 212,
    Description = "<b>Description:</b> Improves Siege Corvette max speed. \n\n<b>Prerequisites:</b> Advanced Research Module and Fighter Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_siegecorvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 1 Siege Corvette",
  },
  {
    Name = "siegecorvetteHealthUpgrade2",
    RequiredResearch = "siegecorvetteHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 225,
    Time = 25,
    DisplayedName = "Siege Corvette Armor 2",
    Description = "<b>Description:</b> Improves Siege Corvette max speed to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Fighter Facility.",
    DisplayPriority = 212,
    Description = "$7566",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_siegecorvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 2 Siege Corvette",
  },
  {
    Name = "siegecorvetteMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 125,
    Time = 20,
    DisplayedName = "Siege Corvette Engine 1",
    DisplayPriority = 213,
    Description = "<b>Description:</b> Improves Siege Corvette max health. \n\n<b>Prerequisites:</b> Advanced Research Module and Fighter Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_siegecorvette",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 Siege Corvette",
  },
  {
    Name = "siegecorvetteMAXSPEEDUpgrade2",
    RequiredResearch = "siegecorvetteMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 225,
    Time = 25,
    DisplayedName = "Siege Corvette Engine 2",
    DisplayPriority = 213,
    Description = "<b>Description:</b> Improves Siege Corvette max health to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Fighter Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_siegecorvette",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 Siege Corvette",
  },
  {
    Name = "TorpedoFrigateHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 300,
    Time = 30,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_TorpedoFrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7244",
  },
  {
    Name = "TorpedoFrigateHealthUpgrade2",
    RequiredResearch = "TorpedoFrigateHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 550,
    Time = 35,
    DisplayedName = "$7573",
    DisplayPriority = 300,
    Description = "$7574",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_TorpedoFrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7245",
  },
  {
    Name = "TorpedoFrigateMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 200,
    Time = 25,
    DisplayedName = "$7575",
    DisplayPriority = 303,
    Description = "$7576",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_TorpedoFrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7244",
  },
  {
    Name = "TorpedoFrigateMAXSPEEDUpgrade2",
    RequiredResearch = "TorpedoFrigateMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 225,
    Time = 35,
    DisplayedName = "$7577",
    DisplayPriority = 303,
    Description = "$7578",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_TorpedoFrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7245",
  },
  {
    Name = "IonCannonFrigateHealthUpgrade1",
    RequiredResearch = "InstaAdvancedFrigateTech",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 300,
    Time = 30,
    DisplayedName = "$7579",
    DisplayPriority = 306,
    Description = "$7580",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_IonCannonFrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7247",
  },
  {
    Name = "IonCannonFrigateHealthUpgrade2",
    RequiredResearch = "IonCannonFrigateHealthUpgrade1 & InstaAdvancedFrigateTech",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 550,
    Time = 35,
    DisplayedName = "$7581",
    DisplayPriority = 306,
    Description = "$7582",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_IonCannonFrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7248",
  },
  {
    Name = "IonCannonFrigateMAXSPEEDUpgrade1",
    RequiredResearch = "InstaAdvancedFrigateTech",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 200,
    Time = 25,
    DisplayedName = "$7583",
    DisplayPriority = 309,
    Description = "$7584",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_IonCannonFrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7247",
  },
  {
    Name = "IonCannonFrigateMAXSPEEDUpgrade2",
    RequiredResearch = "IonCannonFrigateMAXSPEEDUpgrade1 & InstaAdvancedFrigateTech",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 225,
    Time = 35,
    DisplayedName = "$7585",
    DisplayPriority = 309,
    Description = "$7586",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_IonCannonFrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7248",
  },
  {
    Name = "AssaultFrigateHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 300,
    Time = 30,
    DisplayedName = "$7587",
    DisplayPriority = 312,
    Description = "$7588",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultFrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7251",
  },
  {
    Name = "AssaultFrigateHealthUpgrade2",
    RequiredResearch = "AssaultFrigateHealthUpgrade1 & InstaAdvancedFrigateTech",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 550,
    Time = 35,
    DisplayedName = "$7589",
    DisplayPriority = 312,
    Description = "$7590",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultFrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7252",
  },
  {
    Name = "AssaultFrigateMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 200,
    Time = 25,
    DisplayedName = "$7591",
    DisplayPriority = 315,
    Description = "$7592",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultFrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7251",
  },
  {
    Name = "AssaultFrigateMAXSPEEDUpgrade2",
    RequiredResearch = "AssaultFrigateMAXSPEEDUpgrade1 & InstaAdvancedFrigateTech",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 225,
    Time = 35,
    DisplayedName = "$7593",
    DisplayPriority = 315,
    Description = "$7594",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultFrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7252",
  },
  {
    Name = "GunFrigateHealthUpgrade1",
    RequiredResearch = "InstaAdvancedFrigateTech",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 300,
    Time = 30,
    DisplayedName = "Gun Frigate Armor 1",
    DisplayPriority = 316,
    Description = "<b>Description:</b> Improves Gun Frigate Armor. \n\n<b>Prerequisites:</b> Research Module and Frigate Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_GunFrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 1 Gun Frigate",
  },
  {
    Name = "GunFrigateHealthUpgrade2",
    RequiredResearch = "GunFrigateHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 550,
    Time = 35,
    DisplayedName = "Gun Frigate Armor 2",
    DisplayPriority = 316,
    Description = "<b>Description:</b> Improves Gun Frigate Armor to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Frigate Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_GunFrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 2 Gun Frigate",
  },
  {
    Name = "GunFrigateMAXSPEEDUpgrade1",
    RequiredResearch = "InstaAdvancedFrigateTech",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 200,
    Time = 25,
    DisplayedName = "Gun Frigate Engine 1",
    DisplayPriority = 317,
    Description = "<b>Description:</b> Improves Gun Frigate max speed. \n\n<b>Prerequisites:</b> Research Module and Frigate Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_GunFrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 Gun Frigate",
  },
  {
    Name = "GunFrigateMAXSPEEDUpgrade2",
    RequiredResearch = "GunFrigateMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 225,
    Time = 35,
    DisplayedName = "Gun Frigate Engine 2",
    DisplayPriority = 317,
    Description = "<b>Description:</b> Improves Gun Frigate max speed to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Frigate Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_GunFrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 Gun Frigate",
  },
  {
    Name = "SupportFrigateHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 300,
    Time = 30,
    DisplayedName = "Support Frigate Armor 1",
    DisplayPriority = 319,
    Description = "<b>Description:</b> Improves Support Frigate Armor. \n\n<b>Prerequisites:</b> Research Module and Frigate Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_SupportFrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 1 Support Frigate",
  },
  {
    Name = "SupportFrigateHealthUpgrade2",
    RequiredResearch = "SupportFrigateHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 550,
    Time = 35,
    DisplayedName = "Support Frigate Armor 2",
    DisplayPriority = 319,
    Description = "<b>Description:</b> Improves Support Frigate Armor to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Frigate Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_SupportFrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 2 Support Frigate",
  },
  {
    Name = "SupportFrigateMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 200,
    Time = 25,
    DisplayedName = "Support Frigate Engine 1",
    DisplayPriority = 320,
    Description = "<b>Description:</b> Improves Support Frigate max speed. \n\n<b>Prerequisites:</b> Research Module and Frigate Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_SupportFrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 Support Frigate",
  },
  {
    Name = "SupportFrigateMAXSPEEDUpgrade2",
    RequiredResearch = "SupportFrigateMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 225,
    Time = 35,
    DisplayedName = "Support Frigate Engine 2",
    DisplayPriority = 320,
    Description = "<b>Description:</b> Improves Support Frigate max speed to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Frigate Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_SupportFrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 Support Frigate",
  },
  {
    Name = "missilefrigateHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 300,
    Time = 30,
    DisplayedName = "Long Range Missile Frigate Armor 1",
    DisplayPriority = 321,
    Description = "<b>Description:</b> Improves Long Range Missile Frigate Armor. \n\n<b>Prerequisites:</b> Research Module and Frigate Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_missilefrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 1 Long Range Missile Frigate",
  },
  {
    Name = "missilefrigateHealthUpgrade2",
    RequiredResearch = "missilefrigateHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 550,
    Time = 35,
    DisplayedName = "Long Range Missile Frigate Armor 2",
    DisplayPriority = 321,
    Description = "<b>Description:</b> Improves Long Range Missile Frigate Armor to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Frigate Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_missilefrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 2 Long Range Missile Frigate",
  },
  {
    Name = "missilefrigateMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 200,
    Time = 25,
    DisplayedName = "Long Range Missile Frigate Engine 1",
    DisplayPriority = 322,
    Description = "<b>Description:</b> Improves Long Range Missile Frigate max speed. \n\n<b>Prerequisites:</b> Research Module and Frigate Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_missilefrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 Long Range Missile Frigate",
  },
  {
    Name = "missilefrigateMAXSPEEDUpgrade2",
    RequiredResearch = "missilefrigateMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 225,
    Time = 35,
    DisplayedName = "Long Range Missile Frigate Engine 2",
    DisplayPriority = 322,
    Description = "<b>Description:</b> Improves Long Range Missile Frigate max speed to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Frigate Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_missilefrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 Long Range Missile Frigate",
  },
  {
    Name = "plasmafrigateHealthUpgrade1",
    RequiredResearch = "OverclockedFrigatePower",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 300,
    Time = 30,
    DisplayedName = "Plasma Projection Frigate Armor 1",
    DisplayPriority = 323,
    Description = "<b>Description:</b> Improves Plasma Projection Frigate Armor. \n\n<b>Prerequisites:</b> Research Module and Frigate Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_plasmafrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 1 Plasma Projection Frigate",
  },
  {
    Name = "plasmafrigateHealthUpgrade2",
    RequiredResearch = "plasmafrigateHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 550,
    Time = 35,
    DisplayedName = "Plasma Projection Frigate Armor 2",
    DisplayPriority = 323,
    Description = "<b>Description:</b> Improves Plasma Projection Frigate Armor to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Frigate Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_plasmafrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 2 Plasma Projection Frigate",
  },
  {
    Name = "plasmafrigateMAXSPEEDUpgrade1",
    RequiredResearch = "OverclockedFrigatePower",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 200,
    Time = 25,
    DisplayedName = "Plasma Projection Frigate Engine 1",
    DisplayPriority = 324,
    Description = "<b>Description:</b> Improves Plasma Projection Frigate max speed. \n\n<b>Prerequisites:</b> Research Module and Frigate Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_plasmafrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 Plasma Projection Frigate",
  },
  {
    Name = "plasmafrigateMAXSPEEDUpgrade2",
    RequiredResearch = "plasmafrigateMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 225,
    Time = 35,
    DisplayedName = "Plasma Projection Frigate Engine 2",
    DisplayPriority = 324,
    Description = "<b>Description:</b> Improves Plasma Projection Frigate max speed to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Frigate Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_plasmafrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 Plasma Projection Frigate",
  },
  {
    Name = "BattlecruiserHealthUpgrade1",
    RequiredResearch = "BattlecruiserIonWeapons",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 750,
    Time = 30,
    DisplayedName = "$7595",
    DisplayPriority = 401,
    Description = "$7596",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_BattleCruiser",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7254",
  },
  {
    Name = "BattlecruiserHealthUpgrade2",
    RequiredResearch = "BattlecruiserHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 1000,
    Time = 40,
    DisplayedName = "$7597",
    DisplayPriority = 401,
    Description = "$7598",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_BattleCruiser",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7255",
  },
  {
    Name = "BattlecruiserMAXSPEEDUpgrade1",
    RequiredResearch = "BattlecruiserIonWeapons",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 375,
    Time = 15,
    DisplayedName = "$7599",
    DisplayPriority = 402,
    Description = "$7600",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_BattleCruiser",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7254",
  },
  {
    Name = "BattlecruiserMAXSPEEDUpgrade2",
    RequiredResearch = "BattlecruiserMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 600,
    Time = 20,
    DisplayedName = "$7601",
    DisplayPriority = 402,
    Description = "$7602",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_BattleCruiser",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7255",
  },
  {
    Name = "BattleshipHealthUpgrade1",
    RequiredResearch = "BattleshipTech",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 200,
    Time = 30,
    DisplayedName = "Escort Destroyer Hull  1",
    DisplayPriority = 405,
    Description = "<b>Description:</b> Improves Battleship Hulls, allowing them to withstand more damage.  \n\n<b>Prerequisites:</b> Research Module and Capital Ship Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Battleship",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    ShortDisplayedName = "Lvl 1 Escort Destroyer",
    Icon = Icon_Health,
  },
  {
    Name = "BattleshipHealthUpgrade2",
    RequiredResearch = "BattleshipHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 300,
    Time = 35,
    DisplayedName = "Escort Destroyer Hull  2",
    DisplayPriority = 405,
    Description = "<b>Description:</b> Improves Battleship Hulls to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Capital Ship Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Battleship",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 2 Escort Destroyer",
  },
  {
    Name = "BattleshipMAXSPEEDUpgrade1",
    RequiredResearch = "BattleshipTech",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 200,
    Time = 15,
    DisplayedName = "Escort Destroyer Engine 1",
    DisplayPriority = 406,
    Description = "<b>Description:</b> Improves Battleship conventional drive systems. \n\n<b>Prerequisites:</b> Research Module and Capital Ship Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Battleship",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 Escort Destroyer",
  },
  {
    Name = "BattleshipMAXSPEEDUpgrade2",
    RequiredResearch = "BattleshipMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 300,
    Time = 20,
    DisplayedName = "Escort Destroyer Engine 2",
    DisplayPriority = 406,
    Description = "<b>Description:</b> Improves Battleship conventional drive systems to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Capital Ship Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Battleship",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 Escort Destroyer",
  },
  {
    Name = "DestroyerHealthUpgrade1",
    RequiredResearch = "DestroyerTech",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 375,
    Time = 30,
    DisplayedName = "$7639",
    DisplayPriority = 407,
    Description = "$7640",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Destroyer",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    ShortDisplayedName = "$7274",
    Icon = Icon_Health,
  },
  {
    Name = "DestroyerHealthUpgrade2",
    RequiredResearch = "DestroyerHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 600,
    Time = 35,
    DisplayedName = "$7641",
    DisplayPriority = 407,
    Description = "$7642",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Destroyer",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7275",
  },
  {
    Name = "DestroyerMAXSPEEDUpgrade1",
    RequiredResearch = "DestroyerTech",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 375,
    Time = 15,
    DisplayedName = "$7643",
    DisplayPriority = 408,
    Description = "$7644",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Destroyer",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7274",
  },
  {
    Name = "DestroyerMAXSPEEDUpgrade2",
    RequiredResearch = "DestroyerMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 600,
    Time = 20,
    DisplayedName = "$7645",
    DisplayPriority = 408,
    Description = "$7646",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Destroyer",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7275",
  },
  {
    Name = "lightcruiserHealthUpgrade1",
    RequiredResearch = "AssaultCarrierProductionFacilitys",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 375,
    Time = 30,
    DisplayedName = "LightCruiser Hull  1",
    DisplayPriority = 409,
    Description = "<b>Description:</b> Improves Light Cruiser Hulls, allowing them to withstand more damage.  \n\n<b>Prerequisites:</b> Research Module and Capital Ship Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_lightcruiser",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 1 LightCruiser",
  },
  {
    Name = "lightcruiserHealthUpgrade2",
    RequiredResearch = "lightcruiserHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 525,
    Time = 35,
    DisplayedName = "LightCruiser Hull  2",
    DisplayPriority = 409,
    Description = "<b>Description:</b> Improves Light Cruiser Hulls, allowing them to withstand more damage.  \n\n<b>Prerequisites:</b> Advanced Research Module and Capital Ship Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_lightcruiser",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 2 LightCruiser",
  },
  {
    Name = "lightcruiserMAXSPEEDUpgrade1",
    RequiredResearch = "AssaultCarrierProductionFacilitys",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 300,
    Time = 15,
    DisplayedName = "LightCruiser Engine  1",
    DisplayPriority = 410,
    Description = "<b>Description:</b> Improves Light Cruiser conventional drive systems. \n\n<b>Prerequisites:</b> Research Module and Capital Ship Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_lightcruiser",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 LightCruiser",
  },
  {
    Name = "lightcruiserMAXSPEEDUpgrade2",
    RequiredResearch = "lightcruiserMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 400,
    Time = 20,
    DisplayedName = "LightCruiser Engine  2",
    DisplayPriority = 410,
    Description = "<b>Description:</b> Improves Light Cruiser conventional drive systems. \n\n<b>Prerequisites:</b> Advanced Research Module and Capital Ship Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_lightcruiser",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 LightCruiser",
  },
  {
    Name = "lrdestroyerHealthUpgrade1",
    RequiredResearch = "lrdestroyerTech",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 200,
    Time = 30,
    DisplayedName = "Support Destroyer Hull  1",
    DisplayPriority = 413,
    Description = "<b>Description:</b> Improves Support Destroyer Hulls, allowing them to withstand more damage.  \n\n<b>Prerequisites:</b> Research Module and Capital Ship Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_lrdestroyer",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    ShortDisplayedName = "Lvl 1 Support Destroyer",
    Icon = Icon_Health,
  },
  {
    Name = "lrdestroyerHealthUpgrade2",
    RequiredResearch = "lrdestroyerHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 300,
    Time = 35,
    DisplayedName = "Support Destroyer Hull  2",
    DisplayPriority = 413,
    Description = "<b>Description:</b> Improves Support Destroyer Hulls to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Capital Ship Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_lrdestroyer",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 2 Support Destroyer",
  },
  {
    Name = "lrdestroyerMAXSPEEDUpgrade1",
    RequiredResearch = "lrdestroyerTech",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 200,
    Time = 15,
    DisplayedName = "Support Destroyer Engine 1",
    DisplayPriority = 414,
    Description = "<b>Description:</b> Improves Support Destroyer conventional drive systems. \n\n<b>Prerequisites:</b> Research Module and Capital Ship Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_lrdestroyer",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 Support Destroyer",
  },
  {
    Name = "lrdestroyerMAXSPEEDUpgrade2",
    RequiredResearch = "lrdestroyerMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 300,
    Time = 20,
    DisplayedName = "Support Destroyer Engine 2",
    DisplayPriority = 414,
    Description = "<b>Description:</b> Improves Support Destroyer conventional drive systems to Lvl 2. \n\n<b>Prerequisites:</b> Advanced Research Module and Capital Ship Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_lrdestroyer",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 Support Destroyer",
  },
  {
    Name = "CruiserHealthUpgrade1",
    RequiredResearch = "AssaultCarrierProductionFacilitys",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 375,
    Time = 30,
    DisplayedName = "Cruiser Hull  1",
    DisplayPriority = 417,
    Description = "<b>Description:</b> Improves Cruiser Hulls, allowing them to withstand more damage.  \n\n<b>Prerequisites:</b> Research Module and Capital Ship Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Cruiser",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 1 Cruiser",
  },
  {
    Name = "CruiserHealthUpgrade2",
    RequiredResearch = "CruiserHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 525,
    Time = 35,
    DisplayedName = "Cruiser Hull  2",
    DisplayPriority = 417,
    Description = "<b>Description:</b> Improves Cruiser Hulls, allowing them to withstand more damage.  \n\n<b>Prerequisites:</b> Advanced Research Module and Capital Ship Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Cruiser",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 2 Cruiser",
  },
  {
    Name = "CruiserMAXSPEEDUpgrade1",
    RequiredResearch = "AssaultCarrierProductionFacilitys",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 300,
    Time = 15,
    DisplayedName = "Cruiser Engine  1",
    DisplayPriority = 418,
    Description = "<b>Description:</b> Improves Cruiser conventional drive systems. \n\n<b>Prerequisites:</b> Research Module and Capital Ship Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Cruiser",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 1 Cruiser",
  },
  {
    Name = "CruiserMAXSPEEDUpgrade2",
    RequiredResearch = "CruiserMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 400,
    Time = 20,
    DisplayedName = "Cruiser Engine  2",
    DisplayPriority = 418,
    Description = "<b>Description:</b> Improves Cruiser conventional drive systems. \n\n<b>Prerequisites:</b> Advanced Research Module and Capital Ship Facility.",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Cruiser",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "Lvl 2 Cruiser",
  },
  {
    Name = "GunTurretHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & PlatformProduction",
    Cost = 400,
    Time = 30,
    DisplayedName = "$7603",
    DisplayPriority = 600,
    Description = "$7604",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_GunTurret",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7257",
  },
  {
    Name = "GunTurretHealthUpgrade2",
    RequiredResearch = "GunTurretHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & PlatformProduction",
    Cost = 600,
    Time = 40,
    DisplayedName = "$7605",
    DisplayPriority = 600,
    Description = "$7606",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_GunTurret",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7258",
  },
  {
    Name = "PulsarTurretHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & PlatformProduction",
    Cost = 400,
    Time = 30,
    DisplayedName = "Pulsar Turret Hull 1",
    DisplayPriority = 600,
    Description = "<b>Description:</b> Improves Pulsar Turret Hulls, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Research Module and Platform Facility",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_PulsarTurret",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 1 Pulsar Turret",
  },
  {
    Name = "PulsarTurretHealthUpgrade2",
    RequiredResearch = "PulsarTurretHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & PlatformProduction",
    Cost = 600,
    Time = 40,
    DisplayedName = "Pulsar Turret Hull 2",
    DisplayPriority = 600,
    Description = "<b>Description:</b> Improves Pulsar Turret Hulls, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Advanced Research Module and Platform Facility",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_PulsarTurret",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "Lvl 2 Pulsar Turret",
  },
  {
    Name = "IonTurretHealthUpgrade1",
    RequiredResearch = "PlatformIonWeapons",
    RequiredSubSystems = "Research | AdvancedResearch & PlatformProduction",
    Cost = 400,
    Time = 30,
    DisplayedName = "$7607",
    DisplayPriority = 603,
    Description = "$7608",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_IonTurret",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7261",
  },
  {
    Name = "IonTurretHealthUpgrade2",
    RequiredResearch = "IonTurretHealthUpgrade1 & PlatformIonWeapons",
    RequiredSubSystems = "AdvancedResearch & PlatformProduction",
    Cost = 600,
    Time = 40,
    DisplayedName = "$7609",
    DisplayPriority = 603,
    Description = "$7610",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_IonTurret",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7262",
  },
  {
    Name = "ResourceCollectorHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 300,
    Time = 40,
    DisplayedName = "$7611",
    DisplayPriority = 701,
    Description = "$7612",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_ResourceCollector",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.5,
    Icon = Icon_Health,
    ShortDisplayedName = "$7264",
  },
  {
    Name = "ResourceCollectorHealthUpgrade2",
    RequiredResearch = "ResourceCollectorHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 600,
    Time = 60,
    DisplayedName = "$7613",
    DisplayPriority = 701,
    Description = "$7614",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_ResourceCollector",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 2,
    Icon = Icon_Health,
    ShortDisplayedName = "$7265",
  },
  {
    Name = "ResourceControllerHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 400,
    Time = 30,
    DisplayedName = "$7267",
    DisplayPriority = 704,
    Description = "$7616",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_ResourceController",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7267",
  },
  {
    Name = "ResourceControllerHealthUpgrade2",
    RequiredResearch = "ResourceControllerHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 750,
    Time = 40,
    DisplayedName = "$7617",
    DisplayPriority = 704,
    Description = "$7618",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_ResourceController",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7268",
  },
  {
    Name = "HyperspaceCostUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & Hyperspace",
    Cost = 400,
    Time = 45,
    DisplayedName = "$7627",
    DisplayPriority = 1000,
    Description = "$7628",
    UpgradeType = Modifier,
    TargetType = AllShips,
    UpgradeName = "HyperspaceCost",
    UpgradeValue = 0.8,
    TargetName = "Hgn_Mothership",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7280",
  },
  {
    Name = "HyperspaceCostUpgrade2",
    RequiredResearch = "HyperspaceCostUpgrade1",
    RequiredSubSystems = "AdvancedResearch | AdvancedResearch & Hyperspace",
    Cost = 750,
    Time = 60,
    DisplayedName = "$7629",
    DisplayPriority = 1000,
    Description = "$7630",
    UpgradeType = Modifier,
    TargetType = AllShips,
    UpgradeName = "HyperspaceCost",
    UpgradeValue = 0.6,
    TargetName = "Hgn_Mothership",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7281",
  },
  {
    Name = "ShipyardHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & Hyperspace",
    Cost = 300,
    Time = 15,
    DisplayedName = "$7619",
    DisplayPriority = 1200,
    Description = "$7620",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Shipyard",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7271",
  },
  {
    Name = "ShipyardHealthUpgrade2",
    RequiredResearch = "ShipyardHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & Hyperspace",
    Cost = 600,
    Time = 20,
    DisplayedName = "$7621",
    DisplayPriority = 1200,
    Description = "$7622",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Shipyard",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7272",
  },
  {
    Name = "ShipyardMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & Hyperspace",
    Cost = 200,
    Time = 15,
    DisplayedName = "$7623",
    DisplayPriority = 1203,
    Description = "$7624",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Shipyard",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7271",
  },
  {
    Name = "ShipyardMAXSPEEDUpgrade2",
    RequiredResearch = "ShipyardMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & Hyperspace",
    Cost = 600,
    Time = 30,
    DisplayedName = "$7625",
    DisplayPriority = 1203,
    Description = "$7626",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Shipyard",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7272",
  },
  {
    Name = "ShipyardBUILDSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & Hyperspace",
    Cost = 750,
    Time = 40,
    DisplayedName = "$7810",
    DisplayPriority = 1204,
    Description = "$7811",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Shipyard",
    UpgradeName = "BUILDSPEED",
    UpgradeValue = 1.3,
    Icon = Icon_Build,
    ShortDisplayedName = "$7240",
  },
  {
    Name = "EMPResistanceResearch",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 500,
    Time = 60,
    DisplayedName = "EMP Resistance Research",
    DisplayPriority = 1205,
    Description = "<b>Description:</b> Makes Frigates and cap ships less subseptable to EMP weapons. With the new line of Vagyr EMP frigates we need some defensive edge against this new threat. Our researches have come up with this idea but need to work out the kinks. \n\n<b>Prerequisites:</b> Advanced Research Module.",
    TargetName = "Hgn_MotherShip",
    Icon = Icon_Tech,
    ShortDisplayedName = "EMP Resistant Systems",
  },
  {
    Name = "InstaFFAaEMP",
    RequiredResearch = "EMPResistanceResearch",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultFrigate",
    UpgradeName = "MaxShield",
    UpgradeValue = 3.5,
  },
  {
    Name = "InstaFFGaEMP",
    RequiredResearch = "EMPResistanceResearch",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_GunFrigate",
    UpgradeName = "MaxShield",
    UpgradeValue = 3.5,
  },
  {
    Name = "InstaFFTaEMP",
    RequiredResearch = "EMPResistanceResearch",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_TorpedoFrigate",
    UpgradeName = "MaxShield",
    UpgradeValue = 3.5,
  },
  {
    Name = "InstaFFIaEMP",
    RequiredResearch = "EMPResistanceResearch",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_IonCannonFrigate",
    UpgradeName = "MaxShield",
    UpgradeValue = 3.5,
  },
  {
    Name = "InstaFFSaEMP",
    RequiredResearch = "EMPResistanceResearch",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_SupportFrigate",
    UpgradeName = "MaxShield",
    UpgradeValue = 3.5,
  },
  {
    Name = "InstaFFDaEMP",
    RequiredResearch = "EMPResistanceResearch",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_DefenseFieldFrigate",
    UpgradeName = "MaxShield",
    UpgradeValue = 3.5,
  },
  {
    Name = "InstaFFMaEMP",
    RequiredResearch = "EMPResistanceResearch",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MarineFrigate",
    UpgradeName = "MaxShield",
    UpgradeValue = 5.0,
  },
  {
    Name = "InstaDDaEMP",
    RequiredResearch = "EMPResistanceResearch",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Destroyer",
    UpgradeName = "MaxShield",
    UpgradeValue = 3.5,
  },
  {
    Name = "InstaDBSaEMP",
    RequiredResearch = "EMPResistanceResearch",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Battleship",
    UpgradeName = "MaxShield",
    UpgradeValue = 3.5,
  },
  {
    Name = "InstaCACaEMP",
    RequiredResearch = "EMPResistanceResearch",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultCarrier",
    UpgradeName = "MaxShield",
    UpgradeValue = 3.5,
  },
  {
    Name = "InstaCBCaEMP",
    RequiredResearch = "EMPResistanceResearch",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_BattleCruiser",
    UpgradeName = "MaxShield",
    UpgradeValue = 3.5,
  },


  {
    Name = "SensorsDowngrade1",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Sensors Downgrade1",
    DisplayPriority = 1210,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "PrimarySensorsRange",
    UpgradeValue = 0.3,
  },
  {
    Name = "SensorsDowngrade2",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Sensors Downgrade2",
    DisplayPriority = 1211,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "SecondarySensorsRange",
    UpgradeValue = 0.3,
  },
  {
    Name = "SensorsDowngrade3",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Sensors Downgrade3",
    DisplayPriority = 1212,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "VisualRange",
    UpgradeValue = 0.3,
  },
  {
    Name = "SensorsBackToNormal1",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "SensorsBackToNormal1",
    DisplayPriority = 1213,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "PrimarySensorsRange",
    UpgradeValue = 1,
  },
  {
    Name = "SensorsBackToNormal2",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "SensorsBackToNormal2",
    DisplayPriority = 1214,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "SecondarySensorsRange",
    UpgradeValue = 1,
  },
  {
    Name = "SensorsBackToNormal3",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "SensorsBackToNormal3",
    DisplayPriority = 1215,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "VisualRange",
    UpgradeValue = 1,
  },
  {
    Name = "AssaultCorvetteEliteWeaponUpgrade",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Elite Assault Corvette Weapon Upgrade",
    DisplayPriority = 1204,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultCorvetteElite",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 2,
  },
  {
    Name = "AttackBomberEliteWeaponUpgrade",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Elite Attack Bomber Weapon Upgrade",
    DisplayPriority = 1205,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AttackBomberElite",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 1.8,
  },
  {
    Name = "MoverHealthUpgrade",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Mover health upgrade",
    DisplayPriority = 41,
    Description = "Upgrades Mover health",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_Mover",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 5,
  },
  {
    Name = "MoverHealthDowngrade",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Mover health downgrade",
    DisplayPriority = 41,
    Description = "Downgrades Mover health",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_Mover",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1,
  },
  {
    Name = "FrigateHealthUpgradeSPGAME",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 800,
    Time = 60,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 2.5,
  },
  {
    Name = "KeeperHealthUpgradeSPGAME_LOW",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_Destroyer",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 2,
  },
  {
    Name = "KeeperHealthUpgradeSPGAME_MED",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_Destroyer",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 2.5,
  },
  {
    Name = "KeeperHealthUpgradeSPGAME_HIGH",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_Destroyer",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 3,
  },
  {
    Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_1",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 0.1,
  },
  {
    Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_2",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 0.2,
  },
  {
    Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_3",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 0.3,
  },
  {
    Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_4",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 0.4,
  },
  {
    Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_5",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 0.5,
  },
  {
    Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_6",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 0.6,
  },
  {
    Name = "KeeperHealthUpgradeSPGAME_M10_LVL_1",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 2,
  },
  {
    Name = "KeeperHealthUpgradeSPGAME_M10_LVL_2",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 3,
  },
  {
    Name = "KeeperHealthUpgradeSPGAME_M10_LVL_3",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 4,
  },
  {
    Name = "AttackDroidHealthUpgradeSPGAME_LOW",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_AttackDroid",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
  },
  {
    Name = "AttackDroidHealthUpgradeSPGAME_MED",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_AttackDroid",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
  },
  {
    Name = "AttackDroidHealthUpgradeSPGAME_HIGH",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_AttackDroid",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
  },
  {
    Name = "AttackDroidWeaponUpgradeSPGAME_LOW",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_AttackDroid",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 1.2,
  },
  {
    Name = "AttackDroidWeaponUpgradeSPGAME_MED",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_AttackDroid",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 1.4,
  },
  {
    Name = "AttackDroidWeaponUpgradeSPGAME_HIGH",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_AttackDroid",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 1.6,
  },
}