Reinforcements = {
	{Type = "Vgr_Interceptor", Weight = 1}, 
	{Type = "Vgr_MultiroleFighter", Weight = 2}, 
	{Type = "Vgr_HeavyFighter", Weight = 3}, 
	{Type = "Vgr_StrikeFighter", Weight = 2}, 
	{Type = "Vgr_LanceFighter", Weight = 2}, 
	{Type = "Vgr_Defender", Weight = 2}, 
	{Type = "Vgr_HeavyBomber", Weight = 3}, 
	{Type = "Vgr_Bomber", Weight = 2}, 
	{Type = "Vgr_MultilanceCorvette", Weight = 3}, 
	{Type = "Vgr_MissileCorvette", Weight = 3}, 
	{Type = "Vgr_LaserCorvette", Weight = 3},
	{Type = "Vgr_TrinityCorvette", Weight = 3},
	{Type = "Vgr_HeavyMissileFrigate", Weight = 2}, 
	{Type = "Vgr_AssaultFrigate", Weight = 3},
	{Type = "Vgr_GunFrigate", Weight = 3}, 
	{Type = "Vgr_CrusaderFrigate", Weight = 2}, 
	{Type = "Vgr_ArtilleryFrigate", Weight = 2}, 
	{Type = "Vgr_WarFrigate", Weight = 2}, 
	{Type = "Vgr_WarFrigate2", Weight = 2}, 
}